/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.computer.computerDsl.Computer;
import org.xtext.example.computer.computerDsl.ComputerDslPackage;
import org.xtext.example.computer.computerDsl.Drive;
import org.xtext.example.computer.computerDsl.GraphicsCard;
import org.xtext.example.computer.computerDsl.Import;
import org.xtext.example.computer.computerDsl.Memory;
import org.xtext.example.computer.computerDsl.Model;
import org.xtext.example.computer.computerDsl.Motherboard;
import org.xtext.example.computer.computerDsl.PackageDeclaration;
import org.xtext.example.computer.computerDsl.Peripheral;
import org.xtext.example.computer.computerDsl.PowerSupply;
import org.xtext.example.computer.computerDsl.Processor;
import org.xtext.example.computer.computerDsl.Storage;
import org.xtext.example.computer.services.ComputerDslGrammarAccess;

@SuppressWarnings("all")
public class ComputerDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ComputerDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ComputerDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ComputerDslPackage.COMPUTER:
				sequence_Computer(context, (Computer) semanticObject); 
				return; 
			case ComputerDslPackage.DRIVE:
				sequence_Drive(context, (Drive) semanticObject); 
				return; 
			case ComputerDslPackage.GRAPHICS_CARD:
				sequence_GraphicsCard(context, (GraphicsCard) semanticObject); 
				return; 
			case ComputerDslPackage.IMPORT:
				sequence_Import(context, (Import) semanticObject); 
				return; 
			case ComputerDslPackage.MEMORY:
				sequence_Memory(context, (Memory) semanticObject); 
				return; 
			case ComputerDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case ComputerDslPackage.MOTHERBOARD:
				sequence_Motherboard(context, (Motherboard) semanticObject); 
				return; 
			case ComputerDslPackage.PACKAGE_DECLARATION:
				sequence_PackageDeclaration(context, (PackageDeclaration) semanticObject); 
				return; 
			case ComputerDslPackage.PERIPHERAL:
				sequence_Peripheral(context, (Peripheral) semanticObject); 
				return; 
			case ComputerDslPackage.POWER_SUPPLY:
				sequence_PowerSupply(context, (PowerSupply) semanticObject); 
				return; 
			case ComputerDslPackage.PROCESSOR:
				sequence_Processor(context, (Processor) semanticObject); 
				return; 
			case ComputerDslPackage.STORAGE:
				sequence_Storage(context, (Storage) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns Computer
	 *     Computer returns Computer
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         motherboard=[Motherboard|QualifiedName] 
	 *         processor=[Processor|QualifiedName] 
	 *         graphicsCard=[GraphicsCard|QualifiedName]? 
	 *         memory+=[Memory|QualifiedName] 
	 *         memory+=[Memory|QualifiedName]* 
	 *         storage+=[Storage|QualifiedName] 
	 *         storage+=[Storage|QualifiedName]* 
	 *         drive=[Drive|QualifiedName]? 
	 *         (peripherals+=[Peripheral|QualifiedName] peripherals+=[Peripheral|QualifiedName]*)? 
	 *         powerSupply=[PowerSupply|QualifiedName]
	 *     )
	 * </pre>
	 */
	protected void sequence_Computer(ISerializationContext context, Computer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns Drive
	 *     Part returns Drive
	 *     Drive returns Drive
	 *
	 * Constraint:
	 *     (name=ID power=INT type=DriveType)
	 * </pre>
	 */
	protected void sequence_Drive(ISerializationContext context, Drive semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.PART__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.PART__NAME));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.DRIVE__POWER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.DRIVE__POWER));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.DRIVE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.DRIVE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDriveAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getDriveAccess().getPowerINTTerminalRuleCall_4_0(), semanticObject.getPower());
		feeder.accept(grammarAccess.getDriveAccess().getTypeDriveTypeEnumRuleCall_6_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns GraphicsCard
	 *     Part returns GraphicsCard
	 *     GraphicsCard returns GraphicsCard
	 *
	 * Constraint:
	 *     (name=ID power=INT model=STRING? vram=INT)
	 * </pre>
	 */
	protected void sequence_GraphicsCard(ISerializationContext context, GraphicsCard semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns Import
	 *     Import returns Import
	 *
	 * Constraint:
	 *     importedNamespace=QualifiedNameWithWildcard
	 * </pre>
	 */
	protected void sequence_Import(ISerializationContext context, Import semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.IMPORT__IMPORTED_NAMESPACE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.IMPORT__IMPORTED_NAMESPACE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getImportAccess().getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0(), semanticObject.getImportedNamespace());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns Memory
	 *     Part returns Memory
	 *     Memory returns Memory
	 *
	 * Constraint:
	 *     (name=ID power=INT type=MemoryType capacity=INT)
	 * </pre>
	 */
	protected void sequence_Memory(ISerializationContext context, Memory semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.PART__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.PART__NAME));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.MEMORY__POWER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.MEMORY__POWER));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.MEMORY__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.MEMORY__TYPE));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.MEMORY__CAPACITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.MEMORY__CAPACITY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMemoryAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getMemoryAccess().getPowerINTTerminalRuleCall_4_0(), semanticObject.getPower());
		feeder.accept(grammarAccess.getMemoryAccess().getTypeMemoryTypeEnumRuleCall_6_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getMemoryAccess().getCapacityINTTerminalRuleCall_8_0(), semanticObject.getCapacity());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     elements+=AbstractElement+
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns Motherboard
	 *     Part returns Motherboard
	 *     Motherboard returns Motherboard
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         power=INT 
	 *         type=MotherboardType 
	 *         chipset=STRING 
	 *         socket=Socket 
	 *         (ports+=Port ports+=Port*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Motherboard(ISerializationContext context, Motherboard semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns PackageDeclaration
	 *     PackageDeclaration returns PackageDeclaration
	 *
	 * Constraint:
	 *     (name=QualifiedName elements+=AbstractElement*)
	 * </pre>
	 */
	protected void sequence_PackageDeclaration(ISerializationContext context, PackageDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns Peripheral
	 *     Part returns Peripheral
	 *     Peripheral returns Peripheral
	 *
	 * Constraint:
	 *     (kind=PeripheralKind name=ID power=INT port=Port)
	 * </pre>
	 */
	protected void sequence_Peripheral(ISerializationContext context, Peripheral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.PERIPHERAL__KIND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.PERIPHERAL__KIND));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.PART__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.PART__NAME));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.PERIPHERAL__POWER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.PERIPHERAL__POWER));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.PERIPHERAL__PORT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.PERIPHERAL__PORT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPeripheralAccess().getKindPeripheralKindEnumRuleCall_0_0(), semanticObject.getKind());
		feeder.accept(grammarAccess.getPeripheralAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPeripheralAccess().getPowerINTTerminalRuleCall_4_0(), semanticObject.getPower());
		feeder.accept(grammarAccess.getPeripheralAccess().getPortPortEnumRuleCall_6_0(), semanticObject.getPort());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns PowerSupply
	 *     Part returns PowerSupply
	 *     PowerSupply returns PowerSupply
	 *
	 * Constraint:
	 *     (name=ID capacity=INT rating=Rating)
	 * </pre>
	 */
	protected void sequence_PowerSupply(ISerializationContext context, PowerSupply semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.PART__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.PART__NAME));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.POWER_SUPPLY__CAPACITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.POWER_SUPPLY__CAPACITY));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.POWER_SUPPLY__RATING) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.POWER_SUPPLY__RATING));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPowerSupplyAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPowerSupplyAccess().getCapacityINTTerminalRuleCall_4_0(), semanticObject.getCapacity());
		feeder.accept(grammarAccess.getPowerSupplyAccess().getRatingRatingEnumRuleCall_6_0(), semanticObject.getRating());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns Processor
	 *     Part returns Processor
	 *     Processor returns Processor
	 *
	 * Constraint:
	 *     (name=ID power=INT model=STRING? socket=Socket cores=INT)
	 * </pre>
	 */
	protected void sequence_Processor(ISerializationContext context, Processor semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AbstractElement returns Storage
	 *     Part returns Storage
	 *     Storage returns Storage
	 *
	 * Constraint:
	 *     (name=ID power=INT type=StorageType capacity=INT)
	 * </pre>
	 */
	protected void sequence_Storage(ISerializationContext context, Storage semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.PART__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.PART__NAME));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.STORAGE__POWER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.STORAGE__POWER));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.STORAGE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.STORAGE__TYPE));
			if (transientValues.isValueTransient(semanticObject, ComputerDslPackage.Literals.STORAGE__CAPACITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ComputerDslPackage.Literals.STORAGE__CAPACITY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStorageAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getStorageAccess().getPowerINTTerminalRuleCall_4_0(), semanticObject.getPower());
		feeder.accept(grammarAccess.getStorageAccess().getTypeStorageTypeEnumRuleCall_6_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getStorageAccess().getCapacityINTTerminalRuleCall_8_0(), semanticObject.getCapacity());
		feeder.finish();
	}
	
	
}
