#import "_soaws.typ": *
#show: template
= REST vs WS-\*
The main differences between REST and WS-\* (also known as Big Web Services or SOAP/WSDL-based architectures) are articulated across various architectural, conceptual, and technological levels:
== Role of the Web and HTTP Protocol
REST considers the Web as the universal medium for publishing information and uses HTTP as an actual application protocol. Applications expose resources identified by URIs, and clients interact with them using the full semantics of the four HTTP verbs: GET, POST, PUT, and DELETE. WS-\* considers the Web primarily as a universal transport medium for messages. It uses HTTP as a transport-level tunneling protocol to bypass firewalls, exchanging SOAP messages between endpoints, usually relying on a single verb (POST) regardless of the actual operation.
== Interface Definition and Description
REST adopts a uniform and predefined interface. The possible operations are limited to the HTTP verbs, and there is no true standard interface description language; services mostly rely on human-oriented textual documentation. WS-\* uses WSDL (Web Services Description Language), a strongly typed and machine-processable XML language that explicitly defines service contracts and available operations. This allows software tools to automatically generate client code, hiding the complexity of the interaction.
== Transport Flexibility and Message Format
REST is inherently tied to the HTTP protocol. However, it offers great flexibility in the payload format, being able to return representations in XML, JSON, HTML, or even plain text, depending on the client requests. WS-\* is independent of the transport protocol: a message can travel over HTTP, but also over asynchronous protocols like JMS or message queues (MQ), SMTP, or TCP. However, it imposes a single standardized format for messages: XML-based SOAP.
== Complexity and Architectural Decision Management
REST appears simpler because it offers freedom from choice: many decisions are predetermined (e.g., the protocol is always HTTP, the interface is fixed). However, this lack of options often forces developers to implement custom do-it-yourself solutions for advanced features, increasing development costs and technical risks. WS-\* offers freedom of choice, providing a large number of alternatives and standards for defining message exchange patterns, transports, and behaviors. Although it seems more complex, this conceptual richness is well supported by mature tools (SOAP engines and WSDL tools) that handle the low-level work.
== Quality of Service (QoS): Transactions, Security, and Reliability
REST relies on the basic guarantees of the HTTP protocol (best effort delivery) and HTTPS for point-to-point security. It lacks standardized frameworks for managing distributed transactions or reliable messaging. WS-\* includes a suite of optional specifications (e.g., WS-Security, WS-ReliableMessaging, WS-AT for transactions) that guarantee an advanced end-to-end level of service regardless of the underlying transport.
== Ideal Use Cases
In summary, REST is particularly suited for tactical and ad hoc integrations on the Web (e.g., Web 2.0 and Mashup architectures) thanks to its lightweight infrastructure and low barrier to entry. Conversely, WS-\* is the preferred choice for enterprise application integration, where longer lifecycles, interactions with heterogeneous systems (e.g., older mainframes), and strict advanced quality of service requirements are necessary.
