= Service Oriented Architecture
SOA is an architectural approach where a business solution is constructed trough a network of modular, self contained components called services.
= Service Orientation Design Paradigm
In a rapidly expanding market, where the consumer's needs and trends change quickly, business organizations are forced to adapt flexible solutions in order to survive competition. It was therefore vital for them to adopt service orientation in order for them to reap its benefits. SO was a big shift in the way distributed applications are implemented, but enterprises adopted them unusually quickly due to the benefits this change promised. These benefits were partly of economic nature, such as increased ROI and reduced IT burden.\
Services were no longer centralized, and lived in an eco-system of interoperable components.
= Service Compositions
By being composable, services promote component productivity and reusability. In order to be reusable, a service must appropriately allow data exchange (data-flow). There are two data-flow paradigms. With the *blackboard* paradigm, data is stored centrally in a location where all services read their inputs and write their outputs. The main downside of this paradigm is the risk of overriding data. The *explicit data-flow* paradigm makes the data part of the composition. This is achieved trough the use of data connectors that describe how data is manipulated and routed from or to web services.\
A composite application is made trough software components that incapsulate functionalities or UIs, making them reusable while providing a set of operations.
= Service Inventory
A service inventory is an independently standardized and governed collection of complementary services that represents an enterprise or a part of it. An IT enterprise may include a service inventory that represents the extent to which SOA has been adopted. Larger initiatives may even result in the enterprise in its entirety being comprised of an enterprise-wide service inventory. Alternatively, an enterprise environment can contain multiple service inventories, each of which can be individually standardized, governed, and supported by its own service-oriented technology architecture.\
Service inventories are typically created through top-down delivery processes that result in the definition of service inventory blueprints. The subsequent application of service-orientation design principles and custom design standards throughout a service inventory is of great importance in order to establish a high degree of native inter-service interoperability. This supports the repeated creation of effective service compositions.
= Service Oriented Solution Logic
= Services
Services are the basic building brick for SOAs, they are built on open standards and are loosely coupled, so that they can be easily combined with other, more complex services within the enterprise (EAI) or with external entities (B2Bi). Services perform specific business functions such as validating a credit card or generating an invoice. Services are self contained, meaning they include all that is needed to function properly. A consumer may in fact consider them black boxes: they don't care how a service is structured, as long as it functions.
