#show link: it => underline(text(fill: blue, it))
= Service Oriented Architecture
SOA is a way to design software systems by dividing business functionalities into independent, reusable services that can be easily combined to create and modify business processes.
SOA allows a global vision in which components come together, while still providing an overall view of the entire business.
through SOA we can define what type of layers we have inside a horizontally sliced architecture or an eco-system and we can clearly see how this approach is beneficial when compared to the old vertical layer architecture.

*For example* <soa> an e-commerce system can be divided into numerous services, such as:
catalogue,	cart, payment service and delivery service. Each of these components represents a SOA service and every single one performs one well-defined function exposing a clear interface to interact with other services. With this independence it's not required to know how other services are implemented since they can be distributed across different systems or locations. For instance, the payment service can be hosted in Germany, while the delivery service runs on another system.

= Service Orientation Design Paradigm
In a rapidly expanding market, where the consumer's needs and trends change quickly, business organizations are forced to adapt flexible solutions in order to survive competition. It was therefore vital for them to adopt service orientation in order to be commercially viable. SOA was a big shift in the way distributed applications were implemented, but enterprises adopted them unusually quickly due to the benefits this change promised. These benefits were partly of economic nature, such as increased ROI and reduced IT burden. Businesses are willing to spend time and resources (in the short term) if they believe they will gain an advantage in the long term. This is why SOA was adopted, allowing businesses to become non-centralized systems composed of interoperable services within an ecosystem.

*For example* A company that wants to change the payment service of its e-commerce does not need to modify the entire website, as long as the service interface remains the same.

= Service Compositions
By being composable, services promote component productivity and reusability. In order to be reusable, a service must appropriately allow data exchange (data-flow). There are two data-flow paradigms. With the *blackboard* paradigm, data is stored centrally in a location where all services read their inputs and write their outputs. The main downside of this paradigm is the risk of overriding data. The *explicit data-flow* paradigm makes the data part of the composition. This is achieved through the use of data connectors that describe how data is manipulated and routed from or to web services. With this is mind we can point out that a composite application is made through software components that encapsulate functionalities or UIs, making them reusable while providing a set of operations.

*For example* In an e-commerce system, a service composition can be represented by the checkout process, which combines services such as cart, payment, inventory, and delivery. Each service performs a specific task and exchanges data with others to complete the order. Data can be shared using a central repository (blackboard paradigm) or passed explicitly between services (explicit data-flow), making the composition clearer and safer.

= Service Inventory
A service inventory is an independently standardized and governed collection of complementary services that represents an enterprise or a part of it. An IT enterprise may include a service inventory that represents the extent to which SOA has been adopted. Larger initiatives may even result in the enterprise in its entirety being comprised of an enterprise-wide service inventory. Alternatively, an enterprise environment can contain multiple service inventories, each of which can be individually standardized, governed, and supported by its own service-oriented technology architecture and with this method they are typically created through top-down delivery processes that result in the definition of service inventory blueprints. The subsequent application of service-orientation design principles and custom design standards throughout a service inventory is of great importance in order to establish a high degree of native inter-service interoperability. This supports the repeated creation of effective service compositions. \
*For example* In an e-commerce system, a service inventory is the standardized collection of services such as catalogue, cart, payment, order, and delivery. These services are designed following the same service-oriented principles and standards, ensuring interoperability. The service inventory represents the e-commerce domain of the enterprise and supports the creation of service compositions like the checkout process.

= Service Oriented Solution Logic
Service oriented solution logic refers to how code and business rules are organized, partitioned and executed to solve a business problem. In SOA, the business logic isn't contained in one place, it is partitioned between services which are then composed to form the whole business logic.

*An example* is shown in the #link(<soa>)[Service Oriented Architecture] paragraph, where the business logic of the order is not located in a single place.

= Services
Services are the basic building blocks for SOAs, they are built on open standards and are loosely coupled, so that they can be easily combined with other, more complex services within the enterprise (EAI) or with external entities (B2Bi). Services perform specific business functions such as validating a credit card or generating an invoice. Services are self-contained, meaning they include all that is needed to function properly and independently. An important thing to have in mind is the importance of a personal interface, something the consumer may consider black boxes: they don't care how a service is structured, as long as it functions.
Services express their functional capabilities through contracts. They are invoked by sending requests to service endpoints (addresses or URIs) that conform to a specific contract. Service implementation should aim to, regardless of the programming language used, decouple the implementation from the interface definition and hide the implementation from the consumer (black box).
