/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.computer.ide.contentassist.antlr.internal.InternalComputerDslParser;
import org.xtext.example.computer.services.ComputerDslGrammarAccess;

public class ComputerDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ComputerDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ComputerDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAbstractElementAccess().getAlternatives(), "rule__AbstractElement__Alternatives");
			builder.put(grammarAccess.getPartAccess().getAlternatives(), "rule__Part__Alternatives");
			builder.put(grammarAccess.getPeripheralKindAccess().getAlternatives(), "rule__PeripheralKind__Alternatives");
			builder.put(grammarAccess.getMotherboardTypeAccess().getAlternatives(), "rule__MotherboardType__Alternatives");
			builder.put(grammarAccess.getSocketAccess().getAlternatives(), "rule__Socket__Alternatives");
			builder.put(grammarAccess.getPortAccess().getAlternatives(), "rule__Port__Alternatives");
			builder.put(grammarAccess.getMemoryTypeAccess().getAlternatives(), "rule__MemoryType__Alternatives");
			builder.put(grammarAccess.getStorageTypeAccess().getAlternatives(), "rule__StorageType__Alternatives");
			builder.put(grammarAccess.getDriveTypeAccess().getAlternatives(), "rule__DriveType__Alternatives");
			builder.put(grammarAccess.getRatingAccess().getAlternatives(), "rule__Rating__Alternatives");
			builder.put(grammarAccess.getPackageDeclarationAccess().getGroup(), "rule__PackageDeclaration__Group__0");
			builder.put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
			builder.put(grammarAccess.getComputerAccess().getGroup(), "rule__Computer__Group__0");
			builder.put(grammarAccess.getComputerAccess().getGroup_7(), "rule__Computer__Group_7__0");
			builder.put(grammarAccess.getComputerAccess().getGroup_10(), "rule__Computer__Group_10__0");
			builder.put(grammarAccess.getComputerAccess().getGroup_13(), "rule__Computer__Group_13__0");
			builder.put(grammarAccess.getComputerAccess().getGroup_14(), "rule__Computer__Group_14__0");
			builder.put(grammarAccess.getComputerAccess().getGroup_15(), "rule__Computer__Group_15__0");
			builder.put(grammarAccess.getComputerAccess().getGroup_15_2(), "rule__Computer__Group_15_2__0");
			builder.put(grammarAccess.getMotherboardAccess().getGroup(), "rule__Motherboard__Group__0");
			builder.put(grammarAccess.getMotherboardAccess().getGroup_11(), "rule__Motherboard__Group_11__0");
			builder.put(grammarAccess.getMotherboardAccess().getGroup_11_2(), "rule__Motherboard__Group_11_2__0");
			builder.put(grammarAccess.getProcessorAccess().getGroup(), "rule__Processor__Group__0");
			builder.put(grammarAccess.getProcessorAccess().getGroup_5(), "rule__Processor__Group_5__0");
			builder.put(grammarAccess.getGraphicsCardAccess().getGroup(), "rule__GraphicsCard__Group__0");
			builder.put(grammarAccess.getGraphicsCardAccess().getGroup_5(), "rule__GraphicsCard__Group_5__0");
			builder.put(grammarAccess.getMemoryAccess().getGroup(), "rule__Memory__Group__0");
			builder.put(grammarAccess.getStorageAccess().getGroup(), "rule__Storage__Group__0");
			builder.put(grammarAccess.getDriveAccess().getGroup(), "rule__Drive__Group__0");
			builder.put(grammarAccess.getPeripheralAccess().getGroup(), "rule__Peripheral__Group__0");
			builder.put(grammarAccess.getPowerSupplyAccess().getGroup(), "rule__PowerSupply__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementsAssignment(), "rule__Model__ElementsAssignment");
			builder.put(grammarAccess.getPackageDeclarationAccess().getNameAssignment_1(), "rule__PackageDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getPackageDeclarationAccess().getElementsAssignment_3(), "rule__PackageDeclaration__ElementsAssignment_3");
			builder.put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
			builder.put(grammarAccess.getComputerAccess().getNameAssignment_1(), "rule__Computer__NameAssignment_1");
			builder.put(grammarAccess.getComputerAccess().getMotherboardAssignment_4(), "rule__Computer__MotherboardAssignment_4");
			builder.put(grammarAccess.getComputerAccess().getProcessorAssignment_6(), "rule__Computer__ProcessorAssignment_6");
			builder.put(grammarAccess.getComputerAccess().getGraphicsCardAssignment_7_1(), "rule__Computer__GraphicsCardAssignment_7_1");
			builder.put(grammarAccess.getComputerAccess().getMemoryAssignment_9(), "rule__Computer__MemoryAssignment_9");
			builder.put(grammarAccess.getComputerAccess().getMemoryAssignment_10_1(), "rule__Computer__MemoryAssignment_10_1");
			builder.put(grammarAccess.getComputerAccess().getStorageAssignment_12(), "rule__Computer__StorageAssignment_12");
			builder.put(grammarAccess.getComputerAccess().getStorageAssignment_13_1(), "rule__Computer__StorageAssignment_13_1");
			builder.put(grammarAccess.getComputerAccess().getDriveAssignment_14_1(), "rule__Computer__DriveAssignment_14_1");
			builder.put(grammarAccess.getComputerAccess().getPeripheralsAssignment_15_1(), "rule__Computer__PeripheralsAssignment_15_1");
			builder.put(grammarAccess.getComputerAccess().getPeripheralsAssignment_15_2_1(), "rule__Computer__PeripheralsAssignment_15_2_1");
			builder.put(grammarAccess.getComputerAccess().getPowerSupplyAssignment_17(), "rule__Computer__PowerSupplyAssignment_17");
			builder.put(grammarAccess.getMotherboardAccess().getNameAssignment_1(), "rule__Motherboard__NameAssignment_1");
			builder.put(grammarAccess.getMotherboardAccess().getPowerAssignment_4(), "rule__Motherboard__PowerAssignment_4");
			builder.put(grammarAccess.getMotherboardAccess().getTypeAssignment_6(), "rule__Motherboard__TypeAssignment_6");
			builder.put(grammarAccess.getMotherboardAccess().getChipsetAssignment_8(), "rule__Motherboard__ChipsetAssignment_8");
			builder.put(grammarAccess.getMotherboardAccess().getSocketAssignment_10(), "rule__Motherboard__SocketAssignment_10");
			builder.put(grammarAccess.getMotherboardAccess().getPortsAssignment_11_1(), "rule__Motherboard__PortsAssignment_11_1");
			builder.put(grammarAccess.getMotherboardAccess().getPortsAssignment_11_2_1(), "rule__Motherboard__PortsAssignment_11_2_1");
			builder.put(grammarAccess.getProcessorAccess().getNameAssignment_1(), "rule__Processor__NameAssignment_1");
			builder.put(grammarAccess.getProcessorAccess().getPowerAssignment_4(), "rule__Processor__PowerAssignment_4");
			builder.put(grammarAccess.getProcessorAccess().getModelAssignment_5_1(), "rule__Processor__ModelAssignment_5_1");
			builder.put(grammarAccess.getProcessorAccess().getSocketAssignment_7(), "rule__Processor__SocketAssignment_7");
			builder.put(grammarAccess.getProcessorAccess().getCoresAssignment_9(), "rule__Processor__CoresAssignment_9");
			builder.put(grammarAccess.getGraphicsCardAccess().getNameAssignment_1(), "rule__GraphicsCard__NameAssignment_1");
			builder.put(grammarAccess.getGraphicsCardAccess().getPowerAssignment_4(), "rule__GraphicsCard__PowerAssignment_4");
			builder.put(grammarAccess.getGraphicsCardAccess().getModelAssignment_5_1(), "rule__GraphicsCard__ModelAssignment_5_1");
			builder.put(grammarAccess.getGraphicsCardAccess().getVramAssignment_7(), "rule__GraphicsCard__VramAssignment_7");
			builder.put(grammarAccess.getMemoryAccess().getNameAssignment_1(), "rule__Memory__NameAssignment_1");
			builder.put(grammarAccess.getMemoryAccess().getPowerAssignment_4(), "rule__Memory__PowerAssignment_4");
			builder.put(grammarAccess.getMemoryAccess().getTypeAssignment_6(), "rule__Memory__TypeAssignment_6");
			builder.put(grammarAccess.getMemoryAccess().getCapacityAssignment_8(), "rule__Memory__CapacityAssignment_8");
			builder.put(grammarAccess.getStorageAccess().getNameAssignment_1(), "rule__Storage__NameAssignment_1");
			builder.put(grammarAccess.getStorageAccess().getPowerAssignment_4(), "rule__Storage__PowerAssignment_4");
			builder.put(grammarAccess.getStorageAccess().getTypeAssignment_6(), "rule__Storage__TypeAssignment_6");
			builder.put(grammarAccess.getStorageAccess().getCapacityAssignment_8(), "rule__Storage__CapacityAssignment_8");
			builder.put(grammarAccess.getDriveAccess().getNameAssignment_1(), "rule__Drive__NameAssignment_1");
			builder.put(grammarAccess.getDriveAccess().getPowerAssignment_4(), "rule__Drive__PowerAssignment_4");
			builder.put(grammarAccess.getDriveAccess().getTypeAssignment_6(), "rule__Drive__TypeAssignment_6");
			builder.put(grammarAccess.getPeripheralAccess().getKindAssignment_0(), "rule__Peripheral__KindAssignment_0");
			builder.put(grammarAccess.getPeripheralAccess().getNameAssignment_1(), "rule__Peripheral__NameAssignment_1");
			builder.put(grammarAccess.getPeripheralAccess().getPowerAssignment_4(), "rule__Peripheral__PowerAssignment_4");
			builder.put(grammarAccess.getPeripheralAccess().getPortAssignment_6(), "rule__Peripheral__PortAssignment_6");
			builder.put(grammarAccess.getPowerSupplyAccess().getNameAssignment_1(), "rule__PowerSupply__NameAssignment_1");
			builder.put(grammarAccess.getPowerSupplyAccess().getCapacityAssignment_4(), "rule__PowerSupply__CapacityAssignment_4");
			builder.put(grammarAccess.getPowerSupplyAccess().getRatingAssignment_6(), "rule__PowerSupply__RatingAssignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ComputerDslGrammarAccess grammarAccess;

	@Override
	protected InternalComputerDslParser createParser() {
		InternalComputerDslParser result = new InternalComputerDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ComputerDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ComputerDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
