/*
 * generated by Xtext 2.44.0
 */
grammar InternalComputerDsl;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.xtext.example.computer.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.xtext.example.computer.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.xtext.example.computer.services.ComputerDslGrammarAccess;

}

@parser::members {

 	private ComputerDslGrammarAccess grammarAccess;

    public InternalComputerDslParser(TokenStream input, ComputerDslGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Model";
   	}

   	@Override
   	protected ComputerDslGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleModel
entryRuleModel returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getModelRule()); }
	iv_ruleModel=ruleModel
	{ $current=$iv_ruleModel.current; }
	EOF;

// Rule Model
ruleModel returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getModelAccess().getElementsAbstractElementParserRuleCall_0());
			}
			lv_elements_0_0=ruleAbstractElement
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getModelRule());
				}
				add(
					$current,
					"elements",
					lv_elements_0_0,
					"org.xtext.example.computer.ComputerDsl.AbstractElement");
				afterParserOrEnumRuleCall();
			}
		)
	)*
;

// Entry rule entryRuleAbstractElement
entryRuleAbstractElement returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAbstractElementRule()); }
	iv_ruleAbstractElement=ruleAbstractElement
	{ $current=$iv_ruleAbstractElement.current; }
	EOF;

// Rule AbstractElement
ruleAbstractElement returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getPackageDeclarationParserRuleCall_0());
		}
		this_PackageDeclaration_0=rulePackageDeclaration
		{
			$current = $this_PackageDeclaration_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getImportParserRuleCall_1());
		}
		this_Import_1=ruleImport
		{
			$current = $this_Import_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getPartParserRuleCall_2());
		}
		this_Part_2=rulePart
		{
			$current = $this_Part_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getAbstractElementAccess().getComputerParserRuleCall_3());
		}
		this_Computer_3=ruleComputer
		{
			$current = $this_Computer_3.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRulePackageDeclaration
entryRulePackageDeclaration returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPackageDeclarationRule()); }
	iv_rulePackageDeclaration=rulePackageDeclaration
	{ $current=$iv_rulePackageDeclaration.current; }
	EOF;

// Rule PackageDeclaration
rulePackageDeclaration returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='package'
		{
			newLeafNode(otherlv_0, grammarAccess.getPackageDeclarationAccess().getPackageKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPackageDeclarationAccess().getNameQualifiedNameParserRuleCall_1_0());
				}
				lv_name_1_0=ruleQualifiedName
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPackageDeclarationRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"org.xtext.example.computer.ComputerDsl.QualifiedName");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getPackageDeclarationAccess().getLeftCurlyBracketKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPackageDeclarationAccess().getElementsAbstractElementParserRuleCall_3_0());
				}
				lv_elements_3_0=ruleAbstractElement
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPackageDeclarationRule());
					}
					add(
						$current,
						"elements",
						lv_elements_3_0,
						"org.xtext.example.computer.ComputerDsl.AbstractElement");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_4='}'
		{
			newLeafNode(otherlv_4, grammarAccess.getPackageDeclarationAccess().getRightCurlyBracketKeyword_4());
		}
	)
;

// Entry rule entryRuleImport
entryRuleImport returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getImportRule()); }
	iv_ruleImport=ruleImport
	{ $current=$iv_ruleImport.current; }
	EOF;

// Rule Import
ruleImport returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='import'
		{
			newLeafNode(otherlv_0, grammarAccess.getImportAccess().getImportKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getImportAccess().getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0());
				}
				lv_importedNamespace_1_0=ruleQualifiedNameWithWildcard
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getImportRule());
					}
					set(
						$current,
						"importedNamespace",
						lv_importedNamespace_1_0,
						"org.xtext.example.computer.ComputerDsl.QualifiedNameWithWildcard");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleQualifiedName
entryRuleQualifiedName returns [String current=null]:
	{ newCompositeNode(grammarAccess.getQualifiedNameRule()); }
	iv_ruleQualifiedName=ruleQualifiedName
	{ $current=$iv_ruleQualifiedName.current.getText(); }
	EOF;

// Rule QualifiedName
ruleQualifiedName returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_ID_0=RULE_ID
		{
			$current.merge(this_ID_0);
		}
		{
			newLeafNode(this_ID_0, grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_0());
		}
		(
			kw='.'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getQualifiedNameAccess().getFullStopKeyword_1_0());
			}
			this_ID_2=RULE_ID
			{
				$current.merge(this_ID_2);
			}
			{
				newLeafNode(this_ID_2, grammarAccess.getQualifiedNameAccess().getIDTerminalRuleCall_1_1());
			}
		)*
	)
;

// Entry rule entryRuleQualifiedNameWithWildcard
entryRuleQualifiedNameWithWildcard returns [String current=null]:
	{ newCompositeNode(grammarAccess.getQualifiedNameWithWildcardRule()); }
	iv_ruleQualifiedNameWithWildcard=ruleQualifiedNameWithWildcard
	{ $current=$iv_ruleQualifiedNameWithWildcard.current.getText(); }
	EOF;

// Rule QualifiedNameWithWildcard
ruleQualifiedNameWithWildcard returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getQualifiedNameWithWildcardAccess().getQualifiedNameParserRuleCall_0());
		}
		this_QualifiedName_0=ruleQualifiedName
		{
			$current.merge(this_QualifiedName_0);
		}
		{
			afterParserOrEnumRuleCall();
		}
		(
			kw='.*'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getQualifiedNameWithWildcardAccess().getFullStopAsteriskKeyword_1());
			}
		)?
	)
;

// Entry rule entryRuleComputer
entryRuleComputer returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getComputerRule()); }
	iv_ruleComputer=ruleComputer
	{ $current=$iv_ruleComputer.current; }
	EOF;

// Rule Computer
ruleComputer returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='computer'
		{
			newLeafNode(otherlv_0, grammarAccess.getComputerAccess().getComputerKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getComputerAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getComputerRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getComputerAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='motherboard'
		{
			newLeafNode(otherlv_3, grammarAccess.getComputerAccess().getMotherboardKeyword_3());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getComputerRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getComputerAccess().getMotherboardMotherboardCrossReference_4_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='processor'
		{
			newLeafNode(otherlv_5, grammarAccess.getComputerAccess().getProcessorKeyword_5());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getComputerRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getComputerAccess().getProcessorProcessorCrossReference_6_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_7='graphics'
			{
				newLeafNode(otherlv_7, grammarAccess.getComputerAccess().getGraphicsKeyword_7_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getComputerRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getComputerAccess().getGraphicsCardGraphicsCardCrossReference_7_1_0());
					}
					ruleQualifiedName
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_9='memory'
		{
			newLeafNode(otherlv_9, grammarAccess.getComputerAccess().getMemoryKeyword_8());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getComputerRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getComputerAccess().getMemoryMemoryCrossReference_9_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_11=','
			{
				newLeafNode(otherlv_11, grammarAccess.getComputerAccess().getCommaKeyword_10_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getComputerRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getComputerAccess().getMemoryMemoryCrossReference_10_1_0());
					}
					ruleQualifiedName
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_13='storage'
		{
			newLeafNode(otherlv_13, grammarAccess.getComputerAccess().getStorageKeyword_11());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getComputerRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getComputerAccess().getStorageStorageCrossReference_12_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_15=','
			{
				newLeafNode(otherlv_15, grammarAccess.getComputerAccess().getCommaKeyword_13_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getComputerRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getComputerAccess().getStorageStorageCrossReference_13_1_0());
					}
					ruleQualifiedName
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		(
			otherlv_17='drive'
			{
				newLeafNode(otherlv_17, grammarAccess.getComputerAccess().getDriveKeyword_14_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getComputerRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getComputerAccess().getDriveDriveCrossReference_14_1_0());
					}
					ruleQualifiedName
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_19='peripherals'
			{
				newLeafNode(otherlv_19, grammarAccess.getComputerAccess().getPeripheralsKeyword_15_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getComputerRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getComputerAccess().getPeripheralsPeripheralCrossReference_15_1_0());
					}
					ruleQualifiedName
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_21=','
				{
					newLeafNode(otherlv_21, grammarAccess.getComputerAccess().getCommaKeyword_15_2_0());
				}
				(
					(
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getComputerRule());
							}
						}
						{
							newCompositeNode(grammarAccess.getComputerAccess().getPeripheralsPeripheralCrossReference_15_2_1_0());
						}
						ruleQualifiedName
						{
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_23='psu'
		{
			newLeafNode(otherlv_23, grammarAccess.getComputerAccess().getPsuKeyword_16());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getComputerRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getComputerAccess().getPowerSupplyPowerSupplyCrossReference_17_0());
				}
				ruleQualifiedName
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_25='}'
		{
			newLeafNode(otherlv_25, grammarAccess.getComputerAccess().getRightCurlyBracketKeyword_18());
		}
	)
;

// Entry rule entryRulePart
entryRulePart returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPartRule()); }
	iv_rulePart=rulePart
	{ $current=$iv_rulePart.current; }
	EOF;

// Rule Part
rulePart returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getPartAccess().getMotherboardParserRuleCall_0());
		}
		this_Motherboard_0=ruleMotherboard
		{
			$current = $this_Motherboard_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPartAccess().getProcessorParserRuleCall_1());
		}
		this_Processor_1=ruleProcessor
		{
			$current = $this_Processor_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPartAccess().getGraphicsCardParserRuleCall_2());
		}
		this_GraphicsCard_2=ruleGraphicsCard
		{
			$current = $this_GraphicsCard_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPartAccess().getMemoryParserRuleCall_3());
		}
		this_Memory_3=ruleMemory
		{
			$current = $this_Memory_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPartAccess().getStorageParserRuleCall_4());
		}
		this_Storage_4=ruleStorage
		{
			$current = $this_Storage_4.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPartAccess().getDriveParserRuleCall_5());
		}
		this_Drive_5=ruleDrive
		{
			$current = $this_Drive_5.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPartAccess().getPeripheralParserRuleCall_6());
		}
		this_Peripheral_6=rulePeripheral
		{
			$current = $this_Peripheral_6.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPartAccess().getPowerSupplyParserRuleCall_7());
		}
		this_PowerSupply_7=rulePowerSupply
		{
			$current = $this_PowerSupply_7.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleMotherboard
entryRuleMotherboard returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMotherboardRule()); }
	iv_ruleMotherboard=ruleMotherboard
	{ $current=$iv_ruleMotherboard.current; }
	EOF;

// Rule Motherboard
ruleMotherboard returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='motherboard'
		{
			newLeafNode(otherlv_0, grammarAccess.getMotherboardAccess().getMotherboardKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getMotherboardAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getMotherboardRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getMotherboardAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='power'
		{
			newLeafNode(otherlv_3, grammarAccess.getMotherboardAccess().getPowerKeyword_3());
		}
		(
			(
				lv_power_4_0=RULE_INT
				{
					newLeafNode(lv_power_4_0, grammarAccess.getMotherboardAccess().getPowerINTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getMotherboardRule());
					}
					setWithLastConsumed(
						$current,
						"power",
						lv_power_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_5='type'
		{
			newLeafNode(otherlv_5, grammarAccess.getMotherboardAccess().getTypeKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getMotherboardAccess().getTypeMotherboardTypeEnumRuleCall_6_0());
				}
				lv_type_6_0=ruleMotherboardType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMotherboardRule());
					}
					set(
						$current,
						"type",
						lv_type_6_0,
						"org.xtext.example.computer.ComputerDsl.MotherboardType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7='chipset'
		{
			newLeafNode(otherlv_7, grammarAccess.getMotherboardAccess().getChipsetKeyword_7());
		}
		(
			(
				lv_chipset_8_0=RULE_STRING
				{
					newLeafNode(lv_chipset_8_0, grammarAccess.getMotherboardAccess().getChipsetSTRINGTerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getMotherboardRule());
					}
					setWithLastConsumed(
						$current,
						"chipset",
						lv_chipset_8_0,
						"org.eclipse.xtext.common.Terminals.STRING");
				}
			)
		)
		otherlv_9='socket'
		{
			newLeafNode(otherlv_9, grammarAccess.getMotherboardAccess().getSocketKeyword_9());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getMotherboardAccess().getSocketSocketEnumRuleCall_10_0());
				}
				lv_socket_10_0=ruleSocket
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMotherboardRule());
					}
					set(
						$current,
						"socket",
						lv_socket_10_0,
						"org.xtext.example.computer.ComputerDsl.Socket");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_11='ports'
			{
				newLeafNode(otherlv_11, grammarAccess.getMotherboardAccess().getPortsKeyword_11_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getMotherboardAccess().getPortsPortEnumRuleCall_11_1_0());
					}
					lv_ports_12_0=rulePort
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getMotherboardRule());
						}
						add(
							$current,
							"ports",
							lv_ports_12_0,
							"org.xtext.example.computer.ComputerDsl.Port");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_13=','
				{
					newLeafNode(otherlv_13, grammarAccess.getMotherboardAccess().getCommaKeyword_11_2_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getMotherboardAccess().getPortsPortEnumRuleCall_11_2_1_0());
						}
						lv_ports_14_0=rulePort
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getMotherboardRule());
							}
							add(
								$current,
								"ports",
								lv_ports_14_0,
								"org.xtext.example.computer.ComputerDsl.Port");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_15='}'
		{
			newLeafNode(otherlv_15, grammarAccess.getMotherboardAccess().getRightCurlyBracketKeyword_12());
		}
	)
;

// Entry rule entryRuleProcessor
entryRuleProcessor returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getProcessorRule()); }
	iv_ruleProcessor=ruleProcessor
	{ $current=$iv_ruleProcessor.current; }
	EOF;

// Rule Processor
ruleProcessor returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='processor'
		{
			newLeafNode(otherlv_0, grammarAccess.getProcessorAccess().getProcessorKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getProcessorAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getProcessorRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getProcessorAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='power'
		{
			newLeafNode(otherlv_3, grammarAccess.getProcessorAccess().getPowerKeyword_3());
		}
		(
			(
				lv_power_4_0=RULE_INT
				{
					newLeafNode(lv_power_4_0, grammarAccess.getProcessorAccess().getPowerINTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getProcessorRule());
					}
					setWithLastConsumed(
						$current,
						"power",
						lv_power_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			otherlv_5='model'
			{
				newLeafNode(otherlv_5, grammarAccess.getProcessorAccess().getModelKeyword_5_0());
			}
			(
				(
					lv_model_6_0=RULE_STRING
					{
						newLeafNode(lv_model_6_0, grammarAccess.getProcessorAccess().getModelSTRINGTerminalRuleCall_5_1_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getProcessorRule());
						}
						setWithLastConsumed(
							$current,
							"model",
							lv_model_6_0,
							"org.eclipse.xtext.common.Terminals.STRING");
					}
				)
			)
		)?
		otherlv_7='socket'
		{
			newLeafNode(otherlv_7, grammarAccess.getProcessorAccess().getSocketKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getProcessorAccess().getSocketSocketEnumRuleCall_7_0());
				}
				lv_socket_8_0=ruleSocket
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getProcessorRule());
					}
					set(
						$current,
						"socket",
						lv_socket_8_0,
						"org.xtext.example.computer.ComputerDsl.Socket");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_9='cores'
		{
			newLeafNode(otherlv_9, grammarAccess.getProcessorAccess().getCoresKeyword_8());
		}
		(
			(
				lv_cores_10_0=RULE_INT
				{
					newLeafNode(lv_cores_10_0, grammarAccess.getProcessorAccess().getCoresINTTerminalRuleCall_9_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getProcessorRule());
					}
					setWithLastConsumed(
						$current,
						"cores",
						lv_cores_10_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_11='}'
		{
			newLeafNode(otherlv_11, grammarAccess.getProcessorAccess().getRightCurlyBracketKeyword_10());
		}
	)
;

// Entry rule entryRuleGraphicsCard
entryRuleGraphicsCard returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getGraphicsCardRule()); }
	iv_ruleGraphicsCard=ruleGraphicsCard
	{ $current=$iv_ruleGraphicsCard.current; }
	EOF;

// Rule GraphicsCard
ruleGraphicsCard returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='graphics'
		{
			newLeafNode(otherlv_0, grammarAccess.getGraphicsCardAccess().getGraphicsKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getGraphicsCardAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getGraphicsCardRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getGraphicsCardAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='power'
		{
			newLeafNode(otherlv_3, grammarAccess.getGraphicsCardAccess().getPowerKeyword_3());
		}
		(
			(
				lv_power_4_0=RULE_INT
				{
					newLeafNode(lv_power_4_0, grammarAccess.getGraphicsCardAccess().getPowerINTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getGraphicsCardRule());
					}
					setWithLastConsumed(
						$current,
						"power",
						lv_power_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		(
			otherlv_5='model'
			{
				newLeafNode(otherlv_5, grammarAccess.getGraphicsCardAccess().getModelKeyword_5_0());
			}
			(
				(
					lv_model_6_0=RULE_STRING
					{
						newLeafNode(lv_model_6_0, grammarAccess.getGraphicsCardAccess().getModelSTRINGTerminalRuleCall_5_1_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getGraphicsCardRule());
						}
						setWithLastConsumed(
							$current,
							"model",
							lv_model_6_0,
							"org.eclipse.xtext.common.Terminals.STRING");
					}
				)
			)
		)?
		otherlv_7='vram'
		{
			newLeafNode(otherlv_7, grammarAccess.getGraphicsCardAccess().getVramKeyword_6());
		}
		(
			(
				lv_vram_8_0=RULE_INT
				{
					newLeafNode(lv_vram_8_0, grammarAccess.getGraphicsCardAccess().getVramINTTerminalRuleCall_7_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getGraphicsCardRule());
					}
					setWithLastConsumed(
						$current,
						"vram",
						lv_vram_8_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getGraphicsCardAccess().getRightCurlyBracketKeyword_8());
		}
	)
;

// Entry rule entryRuleMemory
entryRuleMemory returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMemoryRule()); }
	iv_ruleMemory=ruleMemory
	{ $current=$iv_ruleMemory.current; }
	EOF;

// Rule Memory
ruleMemory returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='memory'
		{
			newLeafNode(otherlv_0, grammarAccess.getMemoryAccess().getMemoryKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getMemoryAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getMemoryRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getMemoryAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='power'
		{
			newLeafNode(otherlv_3, grammarAccess.getMemoryAccess().getPowerKeyword_3());
		}
		(
			(
				lv_power_4_0=RULE_INT
				{
					newLeafNode(lv_power_4_0, grammarAccess.getMemoryAccess().getPowerINTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getMemoryRule());
					}
					setWithLastConsumed(
						$current,
						"power",
						lv_power_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_5='type'
		{
			newLeafNode(otherlv_5, grammarAccess.getMemoryAccess().getTypeKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getMemoryAccess().getTypeMemoryTypeEnumRuleCall_6_0());
				}
				lv_type_6_0=ruleMemoryType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMemoryRule());
					}
					set(
						$current,
						"type",
						lv_type_6_0,
						"org.xtext.example.computer.ComputerDsl.MemoryType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7='capacity'
		{
			newLeafNode(otherlv_7, grammarAccess.getMemoryAccess().getCapacityKeyword_7());
		}
		(
			(
				lv_capacity_8_0=RULE_INT
				{
					newLeafNode(lv_capacity_8_0, grammarAccess.getMemoryAccess().getCapacityINTTerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getMemoryRule());
					}
					setWithLastConsumed(
						$current,
						"capacity",
						lv_capacity_8_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getMemoryAccess().getRightCurlyBracketKeyword_9());
		}
	)
;

// Entry rule entryRuleStorage
entryRuleStorage returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStorageRule()); }
	iv_ruleStorage=ruleStorage
	{ $current=$iv_ruleStorage.current; }
	EOF;

// Rule Storage
ruleStorage returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='storage'
		{
			newLeafNode(otherlv_0, grammarAccess.getStorageAccess().getStorageKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getStorageAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStorageRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getStorageAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='power'
		{
			newLeafNode(otherlv_3, grammarAccess.getStorageAccess().getPowerKeyword_3());
		}
		(
			(
				lv_power_4_0=RULE_INT
				{
					newLeafNode(lv_power_4_0, grammarAccess.getStorageAccess().getPowerINTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStorageRule());
					}
					setWithLastConsumed(
						$current,
						"power",
						lv_power_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_5='type'
		{
			newLeafNode(otherlv_5, grammarAccess.getStorageAccess().getTypeKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getStorageAccess().getTypeStorageTypeEnumRuleCall_6_0());
				}
				lv_type_6_0=ruleStorageType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getStorageRule());
					}
					set(
						$current,
						"type",
						lv_type_6_0,
						"org.xtext.example.computer.ComputerDsl.StorageType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7='capacity'
		{
			newLeafNode(otherlv_7, grammarAccess.getStorageAccess().getCapacityKeyword_7());
		}
		(
			(
				lv_capacity_8_0=RULE_INT
				{
					newLeafNode(lv_capacity_8_0, grammarAccess.getStorageAccess().getCapacityINTTerminalRuleCall_8_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getStorageRule());
					}
					setWithLastConsumed(
						$current,
						"capacity",
						lv_capacity_8_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_9='}'
		{
			newLeafNode(otherlv_9, grammarAccess.getStorageAccess().getRightCurlyBracketKeyword_9());
		}
	)
;

// Entry rule entryRuleDrive
entryRuleDrive returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDriveRule()); }
	iv_ruleDrive=ruleDrive
	{ $current=$iv_ruleDrive.current; }
	EOF;

// Rule Drive
ruleDrive returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='drive'
		{
			newLeafNode(otherlv_0, grammarAccess.getDriveAccess().getDriveKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getDriveAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDriveRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getDriveAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='power'
		{
			newLeafNode(otherlv_3, grammarAccess.getDriveAccess().getPowerKeyword_3());
		}
		(
			(
				lv_power_4_0=RULE_INT
				{
					newLeafNode(lv_power_4_0, grammarAccess.getDriveAccess().getPowerINTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDriveRule());
					}
					setWithLastConsumed(
						$current,
						"power",
						lv_power_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_5='type'
		{
			newLeafNode(otherlv_5, grammarAccess.getDriveAccess().getTypeKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getDriveAccess().getTypeDriveTypeEnumRuleCall_6_0());
				}
				lv_type_6_0=ruleDriveType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getDriveRule());
					}
					set(
						$current,
						"type",
						lv_type_6_0,
						"org.xtext.example.computer.ComputerDsl.DriveType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getDriveAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRulePeripheral
entryRulePeripheral returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPeripheralRule()); }
	iv_rulePeripheral=rulePeripheral
	{ $current=$iv_rulePeripheral.current; }
	EOF;

// Rule Peripheral
rulePeripheral returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getPeripheralAccess().getKindPeripheralKindEnumRuleCall_0_0());
				}
				lv_kind_0_0=rulePeripheralKind
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPeripheralRule());
					}
					set(
						$current,
						"kind",
						lv_kind_0_0,
						"org.xtext.example.computer.ComputerDsl.PeripheralKind");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getPeripheralAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPeripheralRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getPeripheralAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='power'
		{
			newLeafNode(otherlv_3, grammarAccess.getPeripheralAccess().getPowerKeyword_3());
		}
		(
			(
				lv_power_4_0=RULE_INT
				{
					newLeafNode(lv_power_4_0, grammarAccess.getPeripheralAccess().getPowerINTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPeripheralRule());
					}
					setWithLastConsumed(
						$current,
						"power",
						lv_power_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_5='port'
		{
			newLeafNode(otherlv_5, grammarAccess.getPeripheralAccess().getPortKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPeripheralAccess().getPortPortEnumRuleCall_6_0());
				}
				lv_port_6_0=rulePort
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPeripheralRule());
					}
					set(
						$current,
						"port",
						lv_port_6_0,
						"org.xtext.example.computer.ComputerDsl.Port");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getPeripheralAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Entry rule entryRulePowerSupply
entryRulePowerSupply returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPowerSupplyRule()); }
	iv_rulePowerSupply=rulePowerSupply
	{ $current=$iv_rulePowerSupply.current; }
	EOF;

// Rule PowerSupply
rulePowerSupply returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='psu'
		{
			newLeafNode(otherlv_0, grammarAccess.getPowerSupplyAccess().getPsuKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getPowerSupplyAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPowerSupplyRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getPowerSupplyAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='capacity'
		{
			newLeafNode(otherlv_3, grammarAccess.getPowerSupplyAccess().getCapacityKeyword_3());
		}
		(
			(
				lv_capacity_4_0=RULE_INT
				{
					newLeafNode(lv_capacity_4_0, grammarAccess.getPowerSupplyAccess().getCapacityINTTerminalRuleCall_4_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPowerSupplyRule());
					}
					setWithLastConsumed(
						$current,
						"capacity",
						lv_capacity_4_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
		otherlv_5='rating'
		{
			newLeafNode(otherlv_5, grammarAccess.getPowerSupplyAccess().getRatingKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPowerSupplyAccess().getRatingRatingEnumRuleCall_6_0());
				}
				lv_rating_6_0=ruleRating
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPowerSupplyRule());
					}
					set(
						$current,
						"rating",
						lv_rating_6_0,
						"org.xtext.example.computer.ComputerDsl.Rating");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getPowerSupplyAccess().getRightCurlyBracketKeyword_7());
		}
	)
;

// Rule PeripheralKind
rulePeripheralKind returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='monitor'
			{
				$current = grammarAccess.getPeripheralKindAccess().getMONITOREnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getPeripheralKindAccess().getMONITOREnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='keyboard'
			{
				$current = grammarAccess.getPeripheralKindAccess().getKEYBOARDEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getPeripheralKindAccess().getKEYBOARDEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='mouse'
			{
				$current = grammarAccess.getPeripheralKindAccess().getMOUSEEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getPeripheralKindAccess().getMOUSEEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='printer'
			{
				$current = grammarAccess.getPeripheralKindAccess().getPRINTEREnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getPeripheralKindAccess().getPRINTEREnumLiteralDeclaration_3());
			}
		)
	)
;

// Rule MotherboardType
ruleMotherboardType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='ATX'
			{
				$current = grammarAccess.getMotherboardTypeAccess().getATXEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getMotherboardTypeAccess().getATXEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='MicroATX'
			{
				$current = grammarAccess.getMotherboardTypeAccess().getMicroATXEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getMotherboardTypeAccess().getMicroATXEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='MiniITX'
			{
				$current = grammarAccess.getMotherboardTypeAccess().getMiniITXEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getMotherboardTypeAccess().getMiniITXEnumLiteralDeclaration_2());
			}
		)
	)
;

// Rule Socket
ruleSocket returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='AM4'
			{
				$current = grammarAccess.getSocketAccess().getAM4EnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getSocketAccess().getAM4EnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='AM5'
			{
				$current = grammarAccess.getSocketAccess().getAM5EnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getSocketAccess().getAM5EnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='LGA1200'
			{
				$current = grammarAccess.getSocketAccess().getLGA1200EnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getSocketAccess().getLGA1200EnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='LGA1700'
			{
				$current = grammarAccess.getSocketAccess().getLGA1700EnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getSocketAccess().getLGA1700EnumLiteralDeclaration_3());
			}
		)
	)
;

// Rule Port
rulePort returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='USB'
			{
				$current = grammarAccess.getPortAccess().getUSBEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getPortAccess().getUSBEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='PS2'
			{
				$current = grammarAccess.getPortAccess().getPS2EnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getPortAccess().getPS2EnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='HDMI'
			{
				$current = grammarAccess.getPortAccess().getHDMIEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getPortAccess().getHDMIEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='DisplayPort'
			{
				$current = grammarAccess.getPortAccess().getDisplayPortEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getPortAccess().getDisplayPortEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='VGA'
			{
				$current = grammarAccess.getPortAccess().getVGAEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getPortAccess().getVGAEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='Ethernet'
			{
				$current = grammarAccess.getPortAccess().getEthernetEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getPortAccess().getEthernetEnumLiteralDeclaration_5());
			}
		)
		    |
		(
			enumLiteral_6='Audio'
			{
				$current = grammarAccess.getPortAccess().getAudioEnumLiteralDeclaration_6().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_6, grammarAccess.getPortAccess().getAudioEnumLiteralDeclaration_6());
			}
		)
	)
;

// Rule MemoryType
ruleMemoryType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='DDR4'
			{
				$current = grammarAccess.getMemoryTypeAccess().getDDR4EnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getMemoryTypeAccess().getDDR4EnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='DDR5'
			{
				$current = grammarAccess.getMemoryTypeAccess().getDDR5EnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getMemoryTypeAccess().getDDR5EnumLiteralDeclaration_1());
			}
		)
	)
;

// Rule StorageType
ruleStorageType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='HDD'
			{
				$current = grammarAccess.getStorageTypeAccess().getHDDEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getStorageTypeAccess().getHDDEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='SSD'
			{
				$current = grammarAccess.getStorageTypeAccess().getSSDEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getStorageTypeAccess().getSSDEnumLiteralDeclaration_1());
			}
		)
	)
;

// Rule DriveType
ruleDriveType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='CD_ROM'
			{
				$current = grammarAccess.getDriveTypeAccess().getCD_ROMEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getDriveTypeAccess().getCD_ROMEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='CD_R'
			{
				$current = grammarAccess.getDriveTypeAccess().getCD_REnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getDriveTypeAccess().getCD_REnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='CD_RW'
			{
				$current = grammarAccess.getDriveTypeAccess().getCD_RWEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getDriveTypeAccess().getCD_RWEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='DVD_ROM'
			{
				$current = grammarAccess.getDriveTypeAccess().getDVD_ROMEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getDriveTypeAccess().getDVD_ROMEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='BluRay'
			{
				$current = grammarAccess.getDriveTypeAccess().getBluRayEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getDriveTypeAccess().getBluRayEnumLiteralDeclaration_4());
			}
		)
	)
;

// Rule Rating
ruleRating returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='Bronze'
			{
				$current = grammarAccess.getRatingAccess().getBronzeEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getRatingAccess().getBronzeEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='Silver'
			{
				$current = grammarAccess.getRatingAccess().getSilverEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getRatingAccess().getSilverEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='Gold'
			{
				$current = grammarAccess.getRatingAccess().getGoldEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getRatingAccess().getGoldEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='Platinum'
			{
				$current = grammarAccess.getRatingAccess().getPlatinumEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getRatingAccess().getPlatinumEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='Titanium'
			{
				$current = grammarAccess.getRatingAccess().getTitaniumEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getRatingAccess().getTitaniumEnumLiteralDeclaration_4());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
