/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.computer.computerDsl.ComputerDslFactory
 * @model kind="package"
 * @generated
 */
public interface ComputerDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "computerDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/computer/ComputerDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "computerDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ComputerDslPackage eINSTANCE = org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.ModelImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.AbstractElementImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.PackageDeclarationImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPackageDeclaration()
   * @generated
   */
  int PACKAGE_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION__ELEMENTS = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Package Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PACKAGE_DECLARATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.ImportImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 3;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl <em>Computer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.ComputerImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getComputer()
   * @generated
   */
  int COMPUTER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Motherboard</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER__MOTHERBOARD = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Processor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER__PROCESSOR = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Graphics Card</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER__GRAPHICS_CARD = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Memory</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER__MEMORY = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Storage</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER__STORAGE = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Drive</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER__DRIVE = ABSTRACT_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Peripherals</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER__PERIPHERALS = ABSTRACT_ELEMENT_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Power Supply</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER__POWER_SUPPLY = ABSTRACT_ELEMENT_FEATURE_COUNT + 8;

  /**
   * The number of structural features of the '<em>Computer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 9;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.PartImpl <em>Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.PartImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPart()
   * @generated
   */
  int PART = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PART__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PART_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.MotherboardImpl <em>Motherboard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.MotherboardImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getMotherboard()
   * @generated
   */
  int MOTHERBOARD = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOTHERBOARD__NAME = PART__NAME;

  /**
   * The feature id for the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOTHERBOARD__POWER = PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOTHERBOARD__TYPE = PART_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Chipset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOTHERBOARD__CHIPSET = PART_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Socket</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOTHERBOARD__SOCKET = PART_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Ports</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOTHERBOARD__PORTS = PART_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Motherboard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOTHERBOARD_FEATURE_COUNT = PART_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.ProcessorImpl <em>Processor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.ProcessorImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getProcessor()
   * @generated
   */
  int PROCESSOR = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSOR__NAME = PART__NAME;

  /**
   * The feature id for the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSOR__POWER = PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSOR__MODEL = PART_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Socket</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSOR__SOCKET = PART_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Cores</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSOR__CORES = PART_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Processor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESSOR_FEATURE_COUNT = PART_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.GraphicsCardImpl <em>Graphics Card</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.GraphicsCardImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getGraphicsCard()
   * @generated
   */
  int GRAPHICS_CARD = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHICS_CARD__NAME = PART__NAME;

  /**
   * The feature id for the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHICS_CARD__POWER = PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHICS_CARD__MODEL = PART_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Vram</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHICS_CARD__VRAM = PART_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Graphics Card</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHICS_CARD_FEATURE_COUNT = PART_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.MemoryImpl <em>Memory</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.MemoryImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getMemory()
   * @generated
   */
  int MEMORY = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY__NAME = PART__NAME;

  /**
   * The feature id for the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY__POWER = PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY__TYPE = PART_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY__CAPACITY = PART_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Memory</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEMORY_FEATURE_COUNT = PART_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.StorageImpl <em>Storage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.StorageImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getStorage()
   * @generated
   */
  int STORAGE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE__NAME = PART__NAME;

  /**
   * The feature id for the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE__POWER = PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE__TYPE = PART_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE__CAPACITY = PART_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Storage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORAGE_FEATURE_COUNT = PART_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.DriveImpl <em>Drive</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.DriveImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getDrive()
   * @generated
   */
  int DRIVE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRIVE__NAME = PART__NAME;

  /**
   * The feature id for the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRIVE__POWER = PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRIVE__TYPE = PART_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Drive</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DRIVE_FEATURE_COUNT = PART_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.PeripheralImpl <em>Peripheral</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.PeripheralImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPeripheral()
   * @generated
   */
  int PERIPHERAL = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIPHERAL__NAME = PART__NAME;

  /**
   * The feature id for the '<em><b>Kind</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIPHERAL__KIND = PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIPHERAL__POWER = PART_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Port</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIPHERAL__PORT = PART_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Peripheral</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERIPHERAL_FEATURE_COUNT = PART_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.impl.PowerSupplyImpl <em>Power Supply</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.impl.PowerSupplyImpl
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPowerSupply()
   * @generated
   */
  int POWER_SUPPLY = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POWER_SUPPLY__NAME = PART__NAME;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POWER_SUPPLY__CAPACITY = PART_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rating</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POWER_SUPPLY__RATING = PART_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Power Supply</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POWER_SUPPLY_FEATURE_COUNT = PART_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.PeripheralKind <em>Peripheral Kind</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.PeripheralKind
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPeripheralKind()
   * @generated
   */
  int PERIPHERAL_KIND = 14;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.MotherboardType <em>Motherboard Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.MotherboardType
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getMotherboardType()
   * @generated
   */
  int MOTHERBOARD_TYPE = 15;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.Socket <em>Socket</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.Socket
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getSocket()
   * @generated
   */
  int SOCKET = 16;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.Port <em>Port</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.Port
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPort()
   * @generated
   */
  int PORT = 17;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.MemoryType <em>Memory Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.MemoryType
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getMemoryType()
   * @generated
   */
  int MEMORY_TYPE = 18;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.StorageType <em>Storage Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.StorageType
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getStorageType()
   * @generated
   */
  int STORAGE_TYPE = 19;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.DriveType <em>Drive Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.DriveType
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getDriveType()
   * @generated
   */
  int DRIVE_TYPE = 20;

  /**
   * The meta object id for the '{@link org.xtext.example.computer.computerDsl.Rating <em>Rating</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.computer.computerDsl.Rating
   * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getRating()
   * @generated
   */
  int RATING = 21;


  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.computer.computerDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.computer.computerDsl.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.computer.computerDsl.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.xtext.example.computer.computerDsl.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.PackageDeclaration <em>Package Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Package Declaration</em>'.
   * @see org.xtext.example.computer.computerDsl.PackageDeclaration
   * @generated
   */
  EClass getPackageDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.PackageDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.computer.computerDsl.PackageDeclaration#getName()
   * @see #getPackageDeclaration()
   * @generated
   */
  EAttribute getPackageDeclaration_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.computer.computerDsl.PackageDeclaration#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.example.computer.computerDsl.PackageDeclaration#getElements()
   * @see #getPackageDeclaration()
   * @generated
   */
  EReference getPackageDeclaration_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.xtext.example.computer.computerDsl.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see org.xtext.example.computer.computerDsl.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Computer <em>Computer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Computer</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer
   * @generated
   */
  EClass getComputer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Computer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer#getName()
   * @see #getComputer()
   * @generated
   */
  EAttribute getComputer_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.computer.computerDsl.Computer#getMotherboard <em>Motherboard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Motherboard</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer#getMotherboard()
   * @see #getComputer()
   * @generated
   */
  EReference getComputer_Motherboard();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.computer.computerDsl.Computer#getProcessor <em>Processor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Processor</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer#getProcessor()
   * @see #getComputer()
   * @generated
   */
  EReference getComputer_Processor();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.computer.computerDsl.Computer#getGraphicsCard <em>Graphics Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Graphics Card</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer#getGraphicsCard()
   * @see #getComputer()
   * @generated
   */
  EReference getComputer_GraphicsCard();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.computer.computerDsl.Computer#getMemory <em>Memory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Memory</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer#getMemory()
   * @see #getComputer()
   * @generated
   */
  EReference getComputer_Memory();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.computer.computerDsl.Computer#getStorage <em>Storage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Storage</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer#getStorage()
   * @see #getComputer()
   * @generated
   */
  EReference getComputer_Storage();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.computer.computerDsl.Computer#getDrive <em>Drive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Drive</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer#getDrive()
   * @see #getComputer()
   * @generated
   */
  EReference getComputer_Drive();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.example.computer.computerDsl.Computer#getPeripherals <em>Peripherals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Peripherals</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer#getPeripherals()
   * @see #getComputer()
   * @generated
   */
  EReference getComputer_Peripherals();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.computer.computerDsl.Computer#getPowerSupply <em>Power Supply</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Power Supply</em>'.
   * @see org.xtext.example.computer.computerDsl.Computer#getPowerSupply()
   * @see #getComputer()
   * @generated
   */
  EReference getComputer_PowerSupply();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Part <em>Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Part</em>'.
   * @see org.xtext.example.computer.computerDsl.Part
   * @generated
   */
  EClass getPart();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Part#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.computer.computerDsl.Part#getName()
   * @see #getPart()
   * @generated
   */
  EAttribute getPart_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Motherboard <em>Motherboard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Motherboard</em>'.
   * @see org.xtext.example.computer.computerDsl.Motherboard
   * @generated
   */
  EClass getMotherboard();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Motherboard#getPower <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Power</em>'.
   * @see org.xtext.example.computer.computerDsl.Motherboard#getPower()
   * @see #getMotherboard()
   * @generated
   */
  EAttribute getMotherboard_Power();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Motherboard#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.computer.computerDsl.Motherboard#getType()
   * @see #getMotherboard()
   * @generated
   */
  EAttribute getMotherboard_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Motherboard#getChipset <em>Chipset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Chipset</em>'.
   * @see org.xtext.example.computer.computerDsl.Motherboard#getChipset()
   * @see #getMotherboard()
   * @generated
   */
  EAttribute getMotherboard_Chipset();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Motherboard#getSocket <em>Socket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Socket</em>'.
   * @see org.xtext.example.computer.computerDsl.Motherboard#getSocket()
   * @see #getMotherboard()
   * @generated
   */
  EAttribute getMotherboard_Socket();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.computer.computerDsl.Motherboard#getPorts <em>Ports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Ports</em>'.
   * @see org.xtext.example.computer.computerDsl.Motherboard#getPorts()
   * @see #getMotherboard()
   * @generated
   */
  EAttribute getMotherboard_Ports();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Processor <em>Processor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Processor</em>'.
   * @see org.xtext.example.computer.computerDsl.Processor
   * @generated
   */
  EClass getProcessor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Processor#getPower <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Power</em>'.
   * @see org.xtext.example.computer.computerDsl.Processor#getPower()
   * @see #getProcessor()
   * @generated
   */
  EAttribute getProcessor_Power();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Processor#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Model</em>'.
   * @see org.xtext.example.computer.computerDsl.Processor#getModel()
   * @see #getProcessor()
   * @generated
   */
  EAttribute getProcessor_Model();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Processor#getSocket <em>Socket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Socket</em>'.
   * @see org.xtext.example.computer.computerDsl.Processor#getSocket()
   * @see #getProcessor()
   * @generated
   */
  EAttribute getProcessor_Socket();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Processor#getCores <em>Cores</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cores</em>'.
   * @see org.xtext.example.computer.computerDsl.Processor#getCores()
   * @see #getProcessor()
   * @generated
   */
  EAttribute getProcessor_Cores();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.GraphicsCard <em>Graphics Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphics Card</em>'.
   * @see org.xtext.example.computer.computerDsl.GraphicsCard
   * @generated
   */
  EClass getGraphicsCard();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.GraphicsCard#getPower <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Power</em>'.
   * @see org.xtext.example.computer.computerDsl.GraphicsCard#getPower()
   * @see #getGraphicsCard()
   * @generated
   */
  EAttribute getGraphicsCard_Power();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.GraphicsCard#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Model</em>'.
   * @see org.xtext.example.computer.computerDsl.GraphicsCard#getModel()
   * @see #getGraphicsCard()
   * @generated
   */
  EAttribute getGraphicsCard_Model();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.GraphicsCard#getVram <em>Vram</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vram</em>'.
   * @see org.xtext.example.computer.computerDsl.GraphicsCard#getVram()
   * @see #getGraphicsCard()
   * @generated
   */
  EAttribute getGraphicsCard_Vram();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Memory <em>Memory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Memory</em>'.
   * @see org.xtext.example.computer.computerDsl.Memory
   * @generated
   */
  EClass getMemory();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Memory#getPower <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Power</em>'.
   * @see org.xtext.example.computer.computerDsl.Memory#getPower()
   * @see #getMemory()
   * @generated
   */
  EAttribute getMemory_Power();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Memory#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.computer.computerDsl.Memory#getType()
   * @see #getMemory()
   * @generated
   */
  EAttribute getMemory_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Memory#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see org.xtext.example.computer.computerDsl.Memory#getCapacity()
   * @see #getMemory()
   * @generated
   */
  EAttribute getMemory_Capacity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Storage <em>Storage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Storage</em>'.
   * @see org.xtext.example.computer.computerDsl.Storage
   * @generated
   */
  EClass getStorage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Storage#getPower <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Power</em>'.
   * @see org.xtext.example.computer.computerDsl.Storage#getPower()
   * @see #getStorage()
   * @generated
   */
  EAttribute getStorage_Power();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Storage#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.computer.computerDsl.Storage#getType()
   * @see #getStorage()
   * @generated
   */
  EAttribute getStorage_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Storage#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see org.xtext.example.computer.computerDsl.Storage#getCapacity()
   * @see #getStorage()
   * @generated
   */
  EAttribute getStorage_Capacity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Drive <em>Drive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drive</em>'.
   * @see org.xtext.example.computer.computerDsl.Drive
   * @generated
   */
  EClass getDrive();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Drive#getPower <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Power</em>'.
   * @see org.xtext.example.computer.computerDsl.Drive#getPower()
   * @see #getDrive()
   * @generated
   */
  EAttribute getDrive_Power();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Drive#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.computer.computerDsl.Drive#getType()
   * @see #getDrive()
   * @generated
   */
  EAttribute getDrive_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.Peripheral <em>Peripheral</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Peripheral</em>'.
   * @see org.xtext.example.computer.computerDsl.Peripheral
   * @generated
   */
  EClass getPeripheral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Peripheral#getKind <em>Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Kind</em>'.
   * @see org.xtext.example.computer.computerDsl.Peripheral#getKind()
   * @see #getPeripheral()
   * @generated
   */
  EAttribute getPeripheral_Kind();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Peripheral#getPower <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Power</em>'.
   * @see org.xtext.example.computer.computerDsl.Peripheral#getPower()
   * @see #getPeripheral()
   * @generated
   */
  EAttribute getPeripheral_Power();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.Peripheral#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Port</em>'.
   * @see org.xtext.example.computer.computerDsl.Peripheral#getPort()
   * @see #getPeripheral()
   * @generated
   */
  EAttribute getPeripheral_Port();

  /**
   * Returns the meta object for class '{@link org.xtext.example.computer.computerDsl.PowerSupply <em>Power Supply</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Power Supply</em>'.
   * @see org.xtext.example.computer.computerDsl.PowerSupply
   * @generated
   */
  EClass getPowerSupply();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.PowerSupply#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see org.xtext.example.computer.computerDsl.PowerSupply#getCapacity()
   * @see #getPowerSupply()
   * @generated
   */
  EAttribute getPowerSupply_Capacity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.computer.computerDsl.PowerSupply#getRating <em>Rating</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rating</em>'.
   * @see org.xtext.example.computer.computerDsl.PowerSupply#getRating()
   * @see #getPowerSupply()
   * @generated
   */
  EAttribute getPowerSupply_Rating();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.computer.computerDsl.PeripheralKind <em>Peripheral Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Peripheral Kind</em>'.
   * @see org.xtext.example.computer.computerDsl.PeripheralKind
   * @generated
   */
  EEnum getPeripheralKind();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.computer.computerDsl.MotherboardType <em>Motherboard Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Motherboard Type</em>'.
   * @see org.xtext.example.computer.computerDsl.MotherboardType
   * @generated
   */
  EEnum getMotherboardType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.computer.computerDsl.Socket <em>Socket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Socket</em>'.
   * @see org.xtext.example.computer.computerDsl.Socket
   * @generated
   */
  EEnum getSocket();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.computer.computerDsl.Port <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Port</em>'.
   * @see org.xtext.example.computer.computerDsl.Port
   * @generated
   */
  EEnum getPort();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.computer.computerDsl.MemoryType <em>Memory Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Memory Type</em>'.
   * @see org.xtext.example.computer.computerDsl.MemoryType
   * @generated
   */
  EEnum getMemoryType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.computer.computerDsl.StorageType <em>Storage Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Storage Type</em>'.
   * @see org.xtext.example.computer.computerDsl.StorageType
   * @generated
   */
  EEnum getStorageType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.computer.computerDsl.DriveType <em>Drive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Drive Type</em>'.
   * @see org.xtext.example.computer.computerDsl.DriveType
   * @generated
   */
  EEnum getDriveType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.computer.computerDsl.Rating <em>Rating</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Rating</em>'.
   * @see org.xtext.example.computer.computerDsl.Rating
   * @generated
   */
  EEnum getRating();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ComputerDslFactory getComputerDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.ModelImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.AbstractElementImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.PackageDeclarationImpl <em>Package Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.PackageDeclarationImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPackageDeclaration()
     * @generated
     */
    EClass PACKAGE_DECLARATION = eINSTANCE.getPackageDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PACKAGE_DECLARATION__NAME = eINSTANCE.getPackageDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PACKAGE_DECLARATION__ELEMENTS = eINSTANCE.getPackageDeclaration_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.ImportImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl <em>Computer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.ComputerImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getComputer()
     * @generated
     */
    EClass COMPUTER = eINSTANCE.getComputer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPUTER__NAME = eINSTANCE.getComputer_Name();

    /**
     * The meta object literal for the '<em><b>Motherboard</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPUTER__MOTHERBOARD = eINSTANCE.getComputer_Motherboard();

    /**
     * The meta object literal for the '<em><b>Processor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPUTER__PROCESSOR = eINSTANCE.getComputer_Processor();

    /**
     * The meta object literal for the '<em><b>Graphics Card</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPUTER__GRAPHICS_CARD = eINSTANCE.getComputer_GraphicsCard();

    /**
     * The meta object literal for the '<em><b>Memory</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPUTER__MEMORY = eINSTANCE.getComputer_Memory();

    /**
     * The meta object literal for the '<em><b>Storage</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPUTER__STORAGE = eINSTANCE.getComputer_Storage();

    /**
     * The meta object literal for the '<em><b>Drive</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPUTER__DRIVE = eINSTANCE.getComputer_Drive();

    /**
     * The meta object literal for the '<em><b>Peripherals</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPUTER__PERIPHERALS = eINSTANCE.getComputer_Peripherals();

    /**
     * The meta object literal for the '<em><b>Power Supply</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPUTER__POWER_SUPPLY = eINSTANCE.getComputer_PowerSupply();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.PartImpl <em>Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.PartImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPart()
     * @generated
     */
    EClass PART = eINSTANCE.getPart();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PART__NAME = eINSTANCE.getPart_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.MotherboardImpl <em>Motherboard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.MotherboardImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getMotherboard()
     * @generated
     */
    EClass MOTHERBOARD = eINSTANCE.getMotherboard();

    /**
     * The meta object literal for the '<em><b>Power</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOTHERBOARD__POWER = eINSTANCE.getMotherboard_Power();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOTHERBOARD__TYPE = eINSTANCE.getMotherboard_Type();

    /**
     * The meta object literal for the '<em><b>Chipset</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOTHERBOARD__CHIPSET = eINSTANCE.getMotherboard_Chipset();

    /**
     * The meta object literal for the '<em><b>Socket</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOTHERBOARD__SOCKET = eINSTANCE.getMotherboard_Socket();

    /**
     * The meta object literal for the '<em><b>Ports</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOTHERBOARD__PORTS = eINSTANCE.getMotherboard_Ports();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.ProcessorImpl <em>Processor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.ProcessorImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getProcessor()
     * @generated
     */
    EClass PROCESSOR = eINSTANCE.getProcessor();

    /**
     * The meta object literal for the '<em><b>Power</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESSOR__POWER = eINSTANCE.getProcessor_Power();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESSOR__MODEL = eINSTANCE.getProcessor_Model();

    /**
     * The meta object literal for the '<em><b>Socket</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESSOR__SOCKET = eINSTANCE.getProcessor_Socket();

    /**
     * The meta object literal for the '<em><b>Cores</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESSOR__CORES = eINSTANCE.getProcessor_Cores();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.GraphicsCardImpl <em>Graphics Card</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.GraphicsCardImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getGraphicsCard()
     * @generated
     */
    EClass GRAPHICS_CARD = eINSTANCE.getGraphicsCard();

    /**
     * The meta object literal for the '<em><b>Power</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHICS_CARD__POWER = eINSTANCE.getGraphicsCard_Power();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHICS_CARD__MODEL = eINSTANCE.getGraphicsCard_Model();

    /**
     * The meta object literal for the '<em><b>Vram</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHICS_CARD__VRAM = eINSTANCE.getGraphicsCard_Vram();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.MemoryImpl <em>Memory</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.MemoryImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getMemory()
     * @generated
     */
    EClass MEMORY = eINSTANCE.getMemory();

    /**
     * The meta object literal for the '<em><b>Power</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORY__POWER = eINSTANCE.getMemory_Power();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORY__TYPE = eINSTANCE.getMemory_Type();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEMORY__CAPACITY = eINSTANCE.getMemory_Capacity();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.StorageImpl <em>Storage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.StorageImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getStorage()
     * @generated
     */
    EClass STORAGE = eINSTANCE.getStorage();

    /**
     * The meta object literal for the '<em><b>Power</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE__POWER = eINSTANCE.getStorage_Power();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE__TYPE = eINSTANCE.getStorage_Type();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STORAGE__CAPACITY = eINSTANCE.getStorage_Capacity();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.DriveImpl <em>Drive</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.DriveImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getDrive()
     * @generated
     */
    EClass DRIVE = eINSTANCE.getDrive();

    /**
     * The meta object literal for the '<em><b>Power</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRIVE__POWER = eINSTANCE.getDrive_Power();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DRIVE__TYPE = eINSTANCE.getDrive_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.PeripheralImpl <em>Peripheral</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.PeripheralImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPeripheral()
     * @generated
     */
    EClass PERIPHERAL = eINSTANCE.getPeripheral();

    /**
     * The meta object literal for the '<em><b>Kind</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERIPHERAL__KIND = eINSTANCE.getPeripheral_Kind();

    /**
     * The meta object literal for the '<em><b>Power</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERIPHERAL__POWER = eINSTANCE.getPeripheral_Power();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERIPHERAL__PORT = eINSTANCE.getPeripheral_Port();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.impl.PowerSupplyImpl <em>Power Supply</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.impl.PowerSupplyImpl
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPowerSupply()
     * @generated
     */
    EClass POWER_SUPPLY = eINSTANCE.getPowerSupply();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POWER_SUPPLY__CAPACITY = eINSTANCE.getPowerSupply_Capacity();

    /**
     * The meta object literal for the '<em><b>Rating</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POWER_SUPPLY__RATING = eINSTANCE.getPowerSupply_Rating();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.PeripheralKind <em>Peripheral Kind</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.PeripheralKind
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPeripheralKind()
     * @generated
     */
    EEnum PERIPHERAL_KIND = eINSTANCE.getPeripheralKind();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.MotherboardType <em>Motherboard Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.MotherboardType
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getMotherboardType()
     * @generated
     */
    EEnum MOTHERBOARD_TYPE = eINSTANCE.getMotherboardType();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.Socket <em>Socket</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.Socket
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getSocket()
     * @generated
     */
    EEnum SOCKET = eINSTANCE.getSocket();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.Port <em>Port</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.Port
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getPort()
     * @generated
     */
    EEnum PORT = eINSTANCE.getPort();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.MemoryType <em>Memory Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.MemoryType
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getMemoryType()
     * @generated
     */
    EEnum MEMORY_TYPE = eINSTANCE.getMemoryType();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.StorageType <em>Storage Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.StorageType
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getStorageType()
     * @generated
     */
    EEnum STORAGE_TYPE = eINSTANCE.getStorageType();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.DriveType <em>Drive Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.DriveType
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getDriveType()
     * @generated
     */
    EEnum DRIVE_TYPE = eINSTANCE.getDriveType();

    /**
     * The meta object literal for the '{@link org.xtext.example.computer.computerDsl.Rating <em>Rating</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.computer.computerDsl.Rating
     * @see org.xtext.example.computer.computerDsl.impl.ComputerDslPackageImpl#getRating()
     * @generated
     */
    EEnum RATING = eINSTANCE.getRating();

  }

} //ComputerDslPackage
