/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Drive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.Drive#getPower <em>Power</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Drive#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getDrive()
 * @model
 * @generated
 */
public interface Drive extends Part
{
  /**
   * Returns the value of the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Power</em>' attribute.
   * @see #setPower(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getDrive_Power()
   * @model
   * @generated
   */
  int getPower();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Drive#getPower <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Power</em>' attribute.
   * @see #getPower()
   * @generated
   */
  void setPower(int value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.computer.computerDsl.DriveType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.DriveType
   * @see #setType(DriveType)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getDrive_Type()
   * @model
   * @generated
   */
  DriveType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Drive#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.DriveType
   * @see #getType()
   * @generated
   */
  void setType(DriveType value);

} // Drive
