/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graphics Card</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.GraphicsCard#getPower <em>Power</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.GraphicsCard#getModel <em>Model</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.GraphicsCard#getVram <em>Vram</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getGraphicsCard()
 * @model
 * @generated
 */
public interface GraphicsCard extends Part
{
  /**
   * Returns the value of the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Power</em>' attribute.
   * @see #setPower(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getGraphicsCard_Power()
   * @model
   * @generated
   */
  int getPower();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.GraphicsCard#getPower <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Power</em>' attribute.
   * @see #getPower()
   * @generated
   */
  void setPower(int value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' attribute.
   * @see #setModel(String)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getGraphicsCard_Model()
   * @model
   * @generated
   */
  String getModel();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.GraphicsCard#getModel <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' attribute.
   * @see #getModel()
   * @generated
   */
  void setModel(String value);

  /**
   * Returns the value of the '<em><b>Vram</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vram</em>' attribute.
   * @see #setVram(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getGraphicsCard_Vram()
   * @model
   * @generated
   */
  int getVram();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.GraphicsCard#getVram <em>Vram</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vram</em>' attribute.
   * @see #getVram()
   * @generated
   */
  void setVram(int value);

} // GraphicsCard
