/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Motherboard</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.Motherboard#getPower <em>Power</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Motherboard#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Motherboard#getChipset <em>Chipset</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Motherboard#getSocket <em>Socket</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Motherboard#getPorts <em>Ports</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getMotherboard()
 * @model
 * @generated
 */
public interface Motherboard extends Part
{
  /**
   * Returns the value of the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Power</em>' attribute.
   * @see #setPower(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getMotherboard_Power()
   * @model
   * @generated
   */
  int getPower();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Motherboard#getPower <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Power</em>' attribute.
   * @see #getPower()
   * @generated
   */
  void setPower(int value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.computer.computerDsl.MotherboardType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.MotherboardType
   * @see #setType(MotherboardType)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getMotherboard_Type()
   * @model
   * @generated
   */
  MotherboardType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Motherboard#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.MotherboardType
   * @see #getType()
   * @generated
   */
  void setType(MotherboardType value);

  /**
   * Returns the value of the '<em><b>Chipset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chipset</em>' attribute.
   * @see #setChipset(String)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getMotherboard_Chipset()
   * @model
   * @generated
   */
  String getChipset();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Motherboard#getChipset <em>Chipset</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Chipset</em>' attribute.
   * @see #getChipset()
   * @generated
   */
  void setChipset(String value);

  /**
   * Returns the value of the '<em><b>Socket</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.computer.computerDsl.Socket}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Socket</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.Socket
   * @see #setSocket(Socket)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getMotherboard_Socket()
   * @model
   * @generated
   */
  Socket getSocket();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Motherboard#getSocket <em>Socket</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Socket</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.Socket
   * @see #getSocket()
   * @generated
   */
  void setSocket(Socket value);

  /**
   * Returns the value of the '<em><b>Ports</b></em>' attribute list.
   * The list contents are of type {@link org.xtext.example.computer.computerDsl.Port}.
   * The literals are from the enumeration {@link org.xtext.example.computer.computerDsl.Port}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ports</em>' attribute list.
   * @see org.xtext.example.computer.computerDsl.Port
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getMotherboard_Ports()
   * @model unique="false"
   * @generated
   */
  EList<Port> getPorts();

} // Motherboard
