/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Peripheral Kind</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getPeripheralKind()
 * @model
 * @generated
 */
public enum PeripheralKind implements Enumerator
{
  /**
   * The '<em><b>MONITOR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MONITOR_VALUE
   * @generated
   * @ordered
   */
  MONITOR(0, "MONITOR", "monitor"),

  /**
   * The '<em><b>KEYBOARD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KEYBOARD_VALUE
   * @generated
   * @ordered
   */
  KEYBOARD(1, "KEYBOARD", "keyboard"),

  /**
   * The '<em><b>MOUSE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MOUSE_VALUE
   * @generated
   * @ordered
   */
  MOUSE(2, "MOUSE", "mouse"),

  /**
   * The '<em><b>PRINTER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRINTER_VALUE
   * @generated
   * @ordered
   */
  PRINTER(3, "PRINTER", "printer");

  /**
   * The '<em><b>MONITOR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MONITOR
   * @model literal="monitor"
   * @generated
   * @ordered
   */
  public static final int MONITOR_VALUE = 0;

  /**
   * The '<em><b>KEYBOARD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KEYBOARD
   * @model literal="keyboard"
   * @generated
   * @ordered
   */
  public static final int KEYBOARD_VALUE = 1;

  /**
   * The '<em><b>MOUSE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MOUSE
   * @model literal="mouse"
   * @generated
   * @ordered
   */
  public static final int MOUSE_VALUE = 2;

  /**
   * The '<em><b>PRINTER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRINTER
   * @model literal="printer"
   * @generated
   * @ordered
   */
  public static final int PRINTER_VALUE = 3;

  /**
   * An array of all the '<em><b>Peripheral Kind</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final PeripheralKind[] VALUES_ARRAY =
    new PeripheralKind[]
    {
      MONITOR,
      KEYBOARD,
      MOUSE,
      PRINTER,
    };

  /**
   * A public read-only list of all the '<em><b>Peripheral Kind</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<PeripheralKind> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Peripheral Kind</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PeripheralKind get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PeripheralKind result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Peripheral Kind</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PeripheralKind getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PeripheralKind result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Peripheral Kind</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PeripheralKind get(int value)
  {
    switch (value)
    {
      case MONITOR_VALUE: return MONITOR;
      case KEYBOARD_VALUE: return KEYBOARD;
      case MOUSE_VALUE: return MOUSE;
      case PRINTER_VALUE: return PRINTER;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private PeripheralKind(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //PeripheralKind
