/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Peripheral</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.Peripheral#getKind <em>Kind</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Peripheral#getPower <em>Power</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Peripheral#getPort <em>Port</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getPeripheral()
 * @model
 * @generated
 */
public interface Peripheral extends Part
{
  /**
   * Returns the value of the '<em><b>Kind</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.computer.computerDsl.PeripheralKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kind</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.PeripheralKind
   * @see #setKind(PeripheralKind)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getPeripheral_Kind()
   * @model
   * @generated
   */
  PeripheralKind getKind();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Peripheral#getKind <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kind</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.PeripheralKind
   * @see #getKind()
   * @generated
   */
  void setKind(PeripheralKind value);

  /**
   * Returns the value of the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Power</em>' attribute.
   * @see #setPower(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getPeripheral_Power()
   * @model
   * @generated
   */
  int getPower();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Peripheral#getPower <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Power</em>' attribute.
   * @see #getPower()
   * @generated
   */
  void setPower(int value);

  /**
   * Returns the value of the '<em><b>Port</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.computer.computerDsl.Port}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.Port
   * @see #setPort(Port)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getPeripheral_Port()
   * @model
   * @generated
   */
  Port getPort();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Peripheral#getPort <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.Port
   * @see #getPort()
   * @generated
   */
  void setPort(Port value);

} // Peripheral
