/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Power Supply</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.PowerSupply#getCapacity <em>Capacity</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.PowerSupply#getRating <em>Rating</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getPowerSupply()
 * @model
 * @generated
 */
public interface PowerSupply extends Part
{
  /**
   * Returns the value of the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capacity</em>' attribute.
   * @see #setCapacity(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getPowerSupply_Capacity()
   * @model
   * @generated
   */
  int getCapacity();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.PowerSupply#getCapacity <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capacity</em>' attribute.
   * @see #getCapacity()
   * @generated
   */
  void setCapacity(int value);

  /**
   * Returns the value of the '<em><b>Rating</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.computer.computerDsl.Rating}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rating</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.Rating
   * @see #setRating(Rating)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getPowerSupply_Rating()
   * @model
   * @generated
   */
  Rating getRating();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.PowerSupply#getRating <em>Rating</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rating</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.Rating
   * @see #getRating()
   * @generated
   */
  void setRating(Rating value);

} // PowerSupply
