/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Processor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.Processor#getPower <em>Power</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Processor#getModel <em>Model</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Processor#getSocket <em>Socket</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Processor#getCores <em>Cores</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getProcessor()
 * @model
 * @generated
 */
public interface Processor extends Part
{
  /**
   * Returns the value of the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Power</em>' attribute.
   * @see #setPower(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getProcessor_Power()
   * @model
   * @generated
   */
  int getPower();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Processor#getPower <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Power</em>' attribute.
   * @see #getPower()
   * @generated
   */
  void setPower(int value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' attribute.
   * @see #setModel(String)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getProcessor_Model()
   * @model
   * @generated
   */
  String getModel();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Processor#getModel <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' attribute.
   * @see #getModel()
   * @generated
   */
  void setModel(String value);

  /**
   * Returns the value of the '<em><b>Socket</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.computer.computerDsl.Socket}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Socket</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.Socket
   * @see #setSocket(Socket)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getProcessor_Socket()
   * @model
   * @generated
   */
  Socket getSocket();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Processor#getSocket <em>Socket</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Socket</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.Socket
   * @see #getSocket()
   * @generated
   */
  void setSocket(Socket value);

  /**
   * Returns the value of the '<em><b>Cores</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cores</em>' attribute.
   * @see #setCores(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getProcessor_Cores()
   * @model
   * @generated
   */
  int getCores();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Processor#getCores <em>Cores</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cores</em>' attribute.
   * @see #getCores()
   * @generated
   */
  void setCores(int value);

} // Processor
