/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Storage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.Storage#getPower <em>Power</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Storage#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.Storage#getCapacity <em>Capacity</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getStorage()
 * @model
 * @generated
 */
public interface Storage extends Part
{
  /**
   * Returns the value of the '<em><b>Power</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Power</em>' attribute.
   * @see #setPower(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getStorage_Power()
   * @model
   * @generated
   */
  int getPower();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Storage#getPower <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Power</em>' attribute.
   * @see #getPower()
   * @generated
   */
  void setPower(int value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.computer.computerDsl.StorageType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.StorageType
   * @see #setType(StorageType)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getStorage_Type()
   * @model
   * @generated
   */
  StorageType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Storage#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.computer.computerDsl.StorageType
   * @see #getType()
   * @generated
   */
  void setType(StorageType value);

  /**
   * Returns the value of the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capacity</em>' attribute.
   * @see #setCapacity(int)
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#getStorage_Capacity()
   * @model
   * @generated
   */
  int getCapacity();

  /**
   * Sets the value of the '{@link org.xtext.example.computer.computerDsl.Storage#getCapacity <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capacity</em>' attribute.
   * @see #getCapacity()
   * @generated
   */
  void setCapacity(int value);

} // Storage
