plugins {
	id 'java'
	id 'org.springframework.boot' version '3.1.5'
	id 'io.spring.dependency-management' version '1.1.3'
}

group = 'nl.utwente.soa'
version = '0.0.1-SNAPSHOT'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.shell:spring-shell-starter:3.2.3'
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootRun {
    main = 'nl.utwente.soa.inventoryApplication.InventoryApplication'
    standardInput = System.in
}

test {
	useJUnitPlatform()
}
