/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.computer.ComputerDslRuntimeModule;
import org.xtext.example.computer.ComputerDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ComputerDslIdeSetup extends ComputerDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ComputerDslRuntimeModule(), new ComputerDslIdeModule()));
	}
	
}
