/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.ide;


/**
 * Use this class to register ide components.
 */
public class ComputerDslIdeModule extends AbstractComputerDslIdeModule {
}
