/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ComputerDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Model");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsAbstractElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Model:
		//    (elements+=AbstractElement)*;
		@Override public ParserRule getRule() { return rule; }
		
		//(elements+=AbstractElement)*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_0() { return cElementsAbstractElementParserRuleCall_0; }
	}
	public class AbstractElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.AbstractElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPackageDeclarationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cImportParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPartParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cComputerParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//AbstractElement:
		//    PackageDeclaration | Import | Part | Computer;
		@Override public ParserRule getRule() { return rule; }
		
		//PackageDeclaration | Import | Part | Computer
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PackageDeclaration
		public RuleCall getPackageDeclarationParserRuleCall_0() { return cPackageDeclarationParserRuleCall_0; }
		
		//Import
		public RuleCall getImportParserRuleCall_1() { return cImportParserRuleCall_1; }
		
		//Part
		public RuleCall getPartParserRuleCall_2() { return cPartParserRuleCall_2; }
		
		//Computer
		public RuleCall getComputerParserRuleCall_3() { return cComputerParserRuleCall_3; }
	}
	public class PackageDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.PackageDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPackageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cElementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cElementsAbstractElementParserRuleCall_3_0 = (RuleCall)cElementsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//PackageDeclaration:
		//    'package' name=QualifiedName '{'
		//        (elements+=AbstractElement)*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'package' name=QualifiedName '{'
		//    (elements+=AbstractElement)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'package'
		public Keyword getPackageKeyword_0() { return cPackageKeyword_0; }
		
		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(elements+=AbstractElement)*
		public Assignment getElementsAssignment_3() { return cElementsAssignment_3; }
		
		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_3_0() { return cElementsAbstractElementParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		//Import:
		//    'import' importedNamespace=QualifiedNameWithWildcard;
		@Override public ParserRule getRule() { return rule; }
		
		//'import' importedNamespace=QualifiedNameWithWildcard
		public Group getGroup() { return cGroup; }
		
		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//importedNamespace=QualifiedNameWithWildcard
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }
		
		//QualifiedNameWithWildcard
		public RuleCall getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0() { return cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//    ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class QualifiedNameWithWildcardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.QualifiedNameWithWildcard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//QualifiedNameWithWildcard:
		//    QualifiedName '.*'?;
		@Override public ParserRule getRule() { return rule; }
		
		//QualifiedName '.*'?
		public Group getGroup() { return cGroup; }
		
		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }
		
		//'.*'?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}
	public class ComputerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Computer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComputerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMotherboardKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMotherboardAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cMotherboardMotherboardCrossReference_4_0 = (CrossReference)cMotherboardAssignment_4.eContents().get(0);
		private final RuleCall cMotherboardMotherboardQualifiedNameParserRuleCall_4_0_1 = (RuleCall)cMotherboardMotherboardCrossReference_4_0.eContents().get(1);
		private final Keyword cProcessorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cProcessorAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cProcessorProcessorCrossReference_6_0 = (CrossReference)cProcessorAssignment_6.eContents().get(0);
		private final RuleCall cProcessorProcessorQualifiedNameParserRuleCall_6_0_1 = (RuleCall)cProcessorProcessorCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cGraphicsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cGraphicsCardAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cGraphicsCardGraphicsCardCrossReference_7_1_0 = (CrossReference)cGraphicsCardAssignment_7_1.eContents().get(0);
		private final RuleCall cGraphicsCardGraphicsCardQualifiedNameParserRuleCall_7_1_0_1 = (RuleCall)cGraphicsCardGraphicsCardCrossReference_7_1_0.eContents().get(1);
		private final Keyword cMemoryKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cMemoryAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cMemoryMemoryCrossReference_9_0 = (CrossReference)cMemoryAssignment_9.eContents().get(0);
		private final RuleCall cMemoryMemoryQualifiedNameParserRuleCall_9_0_1 = (RuleCall)cMemoryMemoryCrossReference_9_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cMemoryAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cMemoryMemoryCrossReference_10_1_0 = (CrossReference)cMemoryAssignment_10_1.eContents().get(0);
		private final RuleCall cMemoryMemoryQualifiedNameParserRuleCall_10_1_0_1 = (RuleCall)cMemoryMemoryCrossReference_10_1_0.eContents().get(1);
		private final Keyword cStorageKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cStorageAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final CrossReference cStorageStorageCrossReference_12_0 = (CrossReference)cStorageAssignment_12.eContents().get(0);
		private final RuleCall cStorageStorageQualifiedNameParserRuleCall_12_0_1 = (RuleCall)cStorageStorageCrossReference_12_0.eContents().get(1);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cStorageAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final CrossReference cStorageStorageCrossReference_13_1_0 = (CrossReference)cStorageAssignment_13_1.eContents().get(0);
		private final RuleCall cStorageStorageQualifiedNameParserRuleCall_13_1_0_1 = (RuleCall)cStorageStorageCrossReference_13_1_0.eContents().get(1);
		private final Group cGroup_14 = (Group)cGroup.eContents().get(14);
		private final Keyword cDriveKeyword_14_0 = (Keyword)cGroup_14.eContents().get(0);
		private final Assignment cDriveAssignment_14_1 = (Assignment)cGroup_14.eContents().get(1);
		private final CrossReference cDriveDriveCrossReference_14_1_0 = (CrossReference)cDriveAssignment_14_1.eContents().get(0);
		private final RuleCall cDriveDriveQualifiedNameParserRuleCall_14_1_0_1 = (RuleCall)cDriveDriveCrossReference_14_1_0.eContents().get(1);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cPeripheralsKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cPeripheralsAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final CrossReference cPeripheralsPeripheralCrossReference_15_1_0 = (CrossReference)cPeripheralsAssignment_15_1.eContents().get(0);
		private final RuleCall cPeripheralsPeripheralQualifiedNameParserRuleCall_15_1_0_1 = (RuleCall)cPeripheralsPeripheralCrossReference_15_1_0.eContents().get(1);
		private final Group cGroup_15_2 = (Group)cGroup_15.eContents().get(2);
		private final Keyword cCommaKeyword_15_2_0 = (Keyword)cGroup_15_2.eContents().get(0);
		private final Assignment cPeripheralsAssignment_15_2_1 = (Assignment)cGroup_15_2.eContents().get(1);
		private final CrossReference cPeripheralsPeripheralCrossReference_15_2_1_0 = (CrossReference)cPeripheralsAssignment_15_2_1.eContents().get(0);
		private final RuleCall cPeripheralsPeripheralQualifiedNameParserRuleCall_15_2_1_0_1 = (RuleCall)cPeripheralsPeripheralCrossReference_15_2_1_0.eContents().get(1);
		private final Keyword cPsuKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cPowerSupplyAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final CrossReference cPowerSupplyPowerSupplyCrossReference_17_0 = (CrossReference)cPowerSupplyAssignment_17.eContents().get(0);
		private final RuleCall cPowerSupplyPowerSupplyQualifiedNameParserRuleCall_17_0_1 = (RuleCall)cPowerSupplyPowerSupplyCrossReference_17_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//// A computer only references parts; the parts can live in other packages or files.
		//Computer:
		//    'computer' name=ID '{'
		//        'motherboard' motherboard=[Motherboard|QualifiedName]
		//        'processor' processor=[Processor|QualifiedName]
		//        ('graphics' graphicsCard=[GraphicsCard|QualifiedName])?
		//        'memory' memory+=[Memory|QualifiedName] (',' memory+=[Memory|QualifiedName])*
		//        'storage' storage+=[Storage|QualifiedName] (',' storage+=[Storage|QualifiedName])*
		//        ('drive' drive=[Drive|QualifiedName])?
		//        ('peripherals' peripherals+=[Peripheral|QualifiedName] (',' peripherals+=[Peripheral|QualifiedName])*)?
		//        'psu' powerSupply=[PowerSupply|QualifiedName]
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'computer' name=ID '{'
		//    'motherboard' motherboard=[Motherboard|QualifiedName]
		//    'processor' processor=[Processor|QualifiedName]
		//    ('graphics' graphicsCard=[GraphicsCard|QualifiedName])?
		//    'memory' memory+=[Memory|QualifiedName] (',' memory+=[Memory|QualifiedName])*
		//    'storage' storage+=[Storage|QualifiedName] (',' storage+=[Storage|QualifiedName])*
		//    ('drive' drive=[Drive|QualifiedName])?
		//    ('peripherals' peripherals+=[Peripheral|QualifiedName] (',' peripherals+=[Peripheral|QualifiedName])*)?
		//    'psu' powerSupply=[PowerSupply|QualifiedName]
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'computer'
		public Keyword getComputerKeyword_0() { return cComputerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'motherboard'
		public Keyword getMotherboardKeyword_3() { return cMotherboardKeyword_3; }
		
		//motherboard=[Motherboard|QualifiedName]
		public Assignment getMotherboardAssignment_4() { return cMotherboardAssignment_4; }
		
		//[Motherboard|QualifiedName]
		public CrossReference getMotherboardMotherboardCrossReference_4_0() { return cMotherboardMotherboardCrossReference_4_0; }
		
		//QualifiedName
		public RuleCall getMotherboardMotherboardQualifiedNameParserRuleCall_4_0_1() { return cMotherboardMotherboardQualifiedNameParserRuleCall_4_0_1; }
		
		//'processor'
		public Keyword getProcessorKeyword_5() { return cProcessorKeyword_5; }
		
		//processor=[Processor|QualifiedName]
		public Assignment getProcessorAssignment_6() { return cProcessorAssignment_6; }
		
		//[Processor|QualifiedName]
		public CrossReference getProcessorProcessorCrossReference_6_0() { return cProcessorProcessorCrossReference_6_0; }
		
		//QualifiedName
		public RuleCall getProcessorProcessorQualifiedNameParserRuleCall_6_0_1() { return cProcessorProcessorQualifiedNameParserRuleCall_6_0_1; }
		
		//('graphics' graphicsCard=[GraphicsCard|QualifiedName])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'graphics'
		public Keyword getGraphicsKeyword_7_0() { return cGraphicsKeyword_7_0; }
		
		//graphicsCard=[GraphicsCard|QualifiedName]
		public Assignment getGraphicsCardAssignment_7_1() { return cGraphicsCardAssignment_7_1; }
		
		//[GraphicsCard|QualifiedName]
		public CrossReference getGraphicsCardGraphicsCardCrossReference_7_1_0() { return cGraphicsCardGraphicsCardCrossReference_7_1_0; }
		
		//QualifiedName
		public RuleCall getGraphicsCardGraphicsCardQualifiedNameParserRuleCall_7_1_0_1() { return cGraphicsCardGraphicsCardQualifiedNameParserRuleCall_7_1_0_1; }
		
		//'memory'
		public Keyword getMemoryKeyword_8() { return cMemoryKeyword_8; }
		
		//memory+=[Memory|QualifiedName]
		public Assignment getMemoryAssignment_9() { return cMemoryAssignment_9; }
		
		//[Memory|QualifiedName]
		public CrossReference getMemoryMemoryCrossReference_9_0() { return cMemoryMemoryCrossReference_9_0; }
		
		//QualifiedName
		public RuleCall getMemoryMemoryQualifiedNameParserRuleCall_9_0_1() { return cMemoryMemoryQualifiedNameParserRuleCall_9_0_1; }
		
		//(',' memory+=[Memory|QualifiedName])*
		public Group getGroup_10() { return cGroup_10; }
		
		//','
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//memory+=[Memory|QualifiedName]
		public Assignment getMemoryAssignment_10_1() { return cMemoryAssignment_10_1; }
		
		//[Memory|QualifiedName]
		public CrossReference getMemoryMemoryCrossReference_10_1_0() { return cMemoryMemoryCrossReference_10_1_0; }
		
		//QualifiedName
		public RuleCall getMemoryMemoryQualifiedNameParserRuleCall_10_1_0_1() { return cMemoryMemoryQualifiedNameParserRuleCall_10_1_0_1; }
		
		//'storage'
		public Keyword getStorageKeyword_11() { return cStorageKeyword_11; }
		
		//storage+=[Storage|QualifiedName]
		public Assignment getStorageAssignment_12() { return cStorageAssignment_12; }
		
		//[Storage|QualifiedName]
		public CrossReference getStorageStorageCrossReference_12_0() { return cStorageStorageCrossReference_12_0; }
		
		//QualifiedName
		public RuleCall getStorageStorageQualifiedNameParserRuleCall_12_0_1() { return cStorageStorageQualifiedNameParserRuleCall_12_0_1; }
		
		//(',' storage+=[Storage|QualifiedName])*
		public Group getGroup_13() { return cGroup_13; }
		
		//','
		public Keyword getCommaKeyword_13_0() { return cCommaKeyword_13_0; }
		
		//storage+=[Storage|QualifiedName]
		public Assignment getStorageAssignment_13_1() { return cStorageAssignment_13_1; }
		
		//[Storage|QualifiedName]
		public CrossReference getStorageStorageCrossReference_13_1_0() { return cStorageStorageCrossReference_13_1_0; }
		
		//QualifiedName
		public RuleCall getStorageStorageQualifiedNameParserRuleCall_13_1_0_1() { return cStorageStorageQualifiedNameParserRuleCall_13_1_0_1; }
		
		//('drive' drive=[Drive|QualifiedName])?
		public Group getGroup_14() { return cGroup_14; }
		
		//'drive'
		public Keyword getDriveKeyword_14_0() { return cDriveKeyword_14_0; }
		
		//drive=[Drive|QualifiedName]
		public Assignment getDriveAssignment_14_1() { return cDriveAssignment_14_1; }
		
		//[Drive|QualifiedName]
		public CrossReference getDriveDriveCrossReference_14_1_0() { return cDriveDriveCrossReference_14_1_0; }
		
		//QualifiedName
		public RuleCall getDriveDriveQualifiedNameParserRuleCall_14_1_0_1() { return cDriveDriveQualifiedNameParserRuleCall_14_1_0_1; }
		
		//('peripherals' peripherals+=[Peripheral|QualifiedName] (',' peripherals+=[Peripheral|QualifiedName])*)?
		public Group getGroup_15() { return cGroup_15; }
		
		//'peripherals'
		public Keyword getPeripheralsKeyword_15_0() { return cPeripheralsKeyword_15_0; }
		
		//peripherals+=[Peripheral|QualifiedName]
		public Assignment getPeripheralsAssignment_15_1() { return cPeripheralsAssignment_15_1; }
		
		//[Peripheral|QualifiedName]
		public CrossReference getPeripheralsPeripheralCrossReference_15_1_0() { return cPeripheralsPeripheralCrossReference_15_1_0; }
		
		//QualifiedName
		public RuleCall getPeripheralsPeripheralQualifiedNameParserRuleCall_15_1_0_1() { return cPeripheralsPeripheralQualifiedNameParserRuleCall_15_1_0_1; }
		
		//(',' peripherals+=[Peripheral|QualifiedName])*
		public Group getGroup_15_2() { return cGroup_15_2; }
		
		//','
		public Keyword getCommaKeyword_15_2_0() { return cCommaKeyword_15_2_0; }
		
		//peripherals+=[Peripheral|QualifiedName]
		public Assignment getPeripheralsAssignment_15_2_1() { return cPeripheralsAssignment_15_2_1; }
		
		//[Peripheral|QualifiedName]
		public CrossReference getPeripheralsPeripheralCrossReference_15_2_1_0() { return cPeripheralsPeripheralCrossReference_15_2_1_0; }
		
		//QualifiedName
		public RuleCall getPeripheralsPeripheralQualifiedNameParserRuleCall_15_2_1_0_1() { return cPeripheralsPeripheralQualifiedNameParserRuleCall_15_2_1_0_1; }
		
		//'psu'
		public Keyword getPsuKeyword_16() { return cPsuKeyword_16; }
		
		//powerSupply=[PowerSupply|QualifiedName]
		public Assignment getPowerSupplyAssignment_17() { return cPowerSupplyAssignment_17; }
		
		//[PowerSupply|QualifiedName]
		public CrossReference getPowerSupplyPowerSupplyCrossReference_17_0() { return cPowerSupplyPowerSupplyCrossReference_17_0; }
		
		//QualifiedName
		public RuleCall getPowerSupplyPowerSupplyQualifiedNameParserRuleCall_17_0_1() { return cPowerSupplyPowerSupplyQualifiedNameParserRuleCall_17_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}
	public class PartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Part");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMotherboardParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cProcessorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cGraphicsCardParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMemoryParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cStorageParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cDriveParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cPeripheralParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cPowerSupplyParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Part:
		//    Motherboard | Processor | GraphicsCard | Memory | Storage | Drive | Peripheral | PowerSupply;
		@Override public ParserRule getRule() { return rule; }
		
		//Motherboard | Processor | GraphicsCard | Memory | Storage | Drive | Peripheral | PowerSupply
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Motherboard
		public RuleCall getMotherboardParserRuleCall_0() { return cMotherboardParserRuleCall_0; }
		
		//Processor
		public RuleCall getProcessorParserRuleCall_1() { return cProcessorParserRuleCall_1; }
		
		//GraphicsCard
		public RuleCall getGraphicsCardParserRuleCall_2() { return cGraphicsCardParserRuleCall_2; }
		
		//Memory
		public RuleCall getMemoryParserRuleCall_3() { return cMemoryParserRuleCall_3; }
		
		//Storage
		public RuleCall getStorageParserRuleCall_4() { return cStorageParserRuleCall_4; }
		
		//Drive
		public RuleCall getDriveParserRuleCall_5() { return cDriveParserRuleCall_5; }
		
		//Peripheral
		public RuleCall getPeripheralParserRuleCall_6() { return cPeripheralParserRuleCall_6; }
		
		//PowerSupply
		public RuleCall getPowerSupplyParserRuleCall_7() { return cPowerSupplyParserRuleCall_7; }
	}
	public class MotherboardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Motherboard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMotherboardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPowerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPowerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPowerINTTerminalRuleCall_4_0 = (RuleCall)cPowerAssignment_4.eContents().get(0);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeMotherboardTypeEnumRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Keyword cChipsetKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cChipsetAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cChipsetSTRINGTerminalRuleCall_8_0 = (RuleCall)cChipsetAssignment_8.eContents().get(0);
		private final Keyword cSocketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cSocketAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cSocketSocketEnumRuleCall_10_0 = (RuleCall)cSocketAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cPortsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cPortsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cPortsPortEnumRuleCall_11_1_0 = (RuleCall)cPortsAssignment_11_1.eContents().get(0);
		private final Group cGroup_11_2 = (Group)cGroup_11.eContents().get(2);
		private final Keyword cCommaKeyword_11_2_0 = (Keyword)cGroup_11_2.eContents().get(0);
		private final Assignment cPortsAssignment_11_2_1 = (Assignment)cGroup_11_2.eContents().get(1);
		private final RuleCall cPortsPortEnumRuleCall_11_2_1_0 = (RuleCall)cPortsAssignment_11_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//// power is in watts, vram and capacity of memory/storage in GB
		//Motherboard:
		//    'motherboard' name=ID '{'
		//        'power' power=INT
		//        'type' type=MotherboardType
		//        'chipset' chipset=STRING
		//        'socket' socket=Socket
		//        ('ports' ports+=Port (',' ports+=Port)*)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'motherboard' name=ID '{'
		//    'power' power=INT
		//    'type' type=MotherboardType
		//    'chipset' chipset=STRING
		//    'socket' socket=Socket
		//    ('ports' ports+=Port (',' ports+=Port)*)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'motherboard'
		public Keyword getMotherboardKeyword_0() { return cMotherboardKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'power'
		public Keyword getPowerKeyword_3() { return cPowerKeyword_3; }
		
		//power=INT
		public Assignment getPowerAssignment_4() { return cPowerAssignment_4; }
		
		//INT
		public RuleCall getPowerINTTerminalRuleCall_4_0() { return cPowerINTTerminalRuleCall_4_0; }
		
		//'type'
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }
		
		//type=MotherboardType
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }
		
		//MotherboardType
		public RuleCall getTypeMotherboardTypeEnumRuleCall_6_0() { return cTypeMotherboardTypeEnumRuleCall_6_0; }
		
		//'chipset'
		public Keyword getChipsetKeyword_7() { return cChipsetKeyword_7; }
		
		//chipset=STRING
		public Assignment getChipsetAssignment_8() { return cChipsetAssignment_8; }
		
		//STRING
		public RuleCall getChipsetSTRINGTerminalRuleCall_8_0() { return cChipsetSTRINGTerminalRuleCall_8_0; }
		
		//'socket'
		public Keyword getSocketKeyword_9() { return cSocketKeyword_9; }
		
		//socket=Socket
		public Assignment getSocketAssignment_10() { return cSocketAssignment_10; }
		
		//Socket
		public RuleCall getSocketSocketEnumRuleCall_10_0() { return cSocketSocketEnumRuleCall_10_0; }
		
		//('ports' ports+=Port (',' ports+=Port)*)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'ports'
		public Keyword getPortsKeyword_11_0() { return cPortsKeyword_11_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_11_1() { return cPortsAssignment_11_1; }
		
		//Port
		public RuleCall getPortsPortEnumRuleCall_11_1_0() { return cPortsPortEnumRuleCall_11_1_0; }
		
		//(',' ports+=Port)*
		public Group getGroup_11_2() { return cGroup_11_2; }
		
		//','
		public Keyword getCommaKeyword_11_2_0() { return cCommaKeyword_11_2_0; }
		
		//ports+=Port
		public Assignment getPortsAssignment_11_2_1() { return cPortsAssignment_11_2_1; }
		
		//Port
		public RuleCall getPortsPortEnumRuleCall_11_2_1_0() { return cPortsPortEnumRuleCall_11_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class ProcessorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Processor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcessorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPowerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPowerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPowerINTTerminalRuleCall_4_0 = (RuleCall)cPowerAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cModelKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cModelAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cModelSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cModelAssignment_5_1.eContents().get(0);
		private final Keyword cSocketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cSocketAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cSocketSocketEnumRuleCall_7_0 = (RuleCall)cSocketAssignment_7.eContents().get(0);
		private final Keyword cCoresKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cCoresAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cCoresINTTerminalRuleCall_9_0 = (RuleCall)cCoresAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Processor:
		//    'processor' name=ID '{'
		//        'power' power=INT
		//        ('model' model=STRING)?
		//        'socket' socket=Socket
		//        'cores' cores=INT
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'processor' name=ID '{'
		//    'power' power=INT
		//    ('model' model=STRING)?
		//    'socket' socket=Socket
		//    'cores' cores=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'processor'
		public Keyword getProcessorKeyword_0() { return cProcessorKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'power'
		public Keyword getPowerKeyword_3() { return cPowerKeyword_3; }
		
		//power=INT
		public Assignment getPowerAssignment_4() { return cPowerAssignment_4; }
		
		//INT
		public RuleCall getPowerINTTerminalRuleCall_4_0() { return cPowerINTTerminalRuleCall_4_0; }
		
		//('model' model=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'model'
		public Keyword getModelKeyword_5_0() { return cModelKeyword_5_0; }
		
		//model=STRING
		public Assignment getModelAssignment_5_1() { return cModelAssignment_5_1; }
		
		//STRING
		public RuleCall getModelSTRINGTerminalRuleCall_5_1_0() { return cModelSTRINGTerminalRuleCall_5_1_0; }
		
		//'socket'
		public Keyword getSocketKeyword_6() { return cSocketKeyword_6; }
		
		//socket=Socket
		public Assignment getSocketAssignment_7() { return cSocketAssignment_7; }
		
		//Socket
		public RuleCall getSocketSocketEnumRuleCall_7_0() { return cSocketSocketEnumRuleCall_7_0; }
		
		//'cores'
		public Keyword getCoresKeyword_8() { return cCoresKeyword_8; }
		
		//cores=INT
		public Assignment getCoresAssignment_9() { return cCoresAssignment_9; }
		
		//INT
		public RuleCall getCoresINTTerminalRuleCall_9_0() { return cCoresINTTerminalRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class GraphicsCardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.GraphicsCard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGraphicsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPowerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPowerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPowerINTTerminalRuleCall_4_0 = (RuleCall)cPowerAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cModelKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cModelAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cModelSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cModelAssignment_5_1.eContents().get(0);
		private final Keyword cVramKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cVramAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cVramINTTerminalRuleCall_7_0 = (RuleCall)cVramAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//GraphicsCard:
		//    'graphics' name=ID '{'
		//        'power' power=INT
		//        ('model' model=STRING)?
		//        'vram' vram=INT
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'graphics' name=ID '{'
		//    'power' power=INT
		//    ('model' model=STRING)?
		//    'vram' vram=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'graphics'
		public Keyword getGraphicsKeyword_0() { return cGraphicsKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'power'
		public Keyword getPowerKeyword_3() { return cPowerKeyword_3; }
		
		//power=INT
		public Assignment getPowerAssignment_4() { return cPowerAssignment_4; }
		
		//INT
		public RuleCall getPowerINTTerminalRuleCall_4_0() { return cPowerINTTerminalRuleCall_4_0; }
		
		//('model' model=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'model'
		public Keyword getModelKeyword_5_0() { return cModelKeyword_5_0; }
		
		//model=STRING
		public Assignment getModelAssignment_5_1() { return cModelAssignment_5_1; }
		
		//STRING
		public RuleCall getModelSTRINGTerminalRuleCall_5_1_0() { return cModelSTRINGTerminalRuleCall_5_1_0; }
		
		//'vram'
		public Keyword getVramKeyword_6() { return cVramKeyword_6; }
		
		//vram=INT
		public Assignment getVramAssignment_7() { return cVramAssignment_7; }
		
		//INT
		public RuleCall getVramINTTerminalRuleCall_7_0() { return cVramINTTerminalRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class MemoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Memory");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMemoryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPowerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPowerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPowerINTTerminalRuleCall_4_0 = (RuleCall)cPowerAssignment_4.eContents().get(0);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeMemoryTypeEnumRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Keyword cCapacityKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cCapacityAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cCapacityINTTerminalRuleCall_8_0 = (RuleCall)cCapacityAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Memory:
		//    'memory' name=ID '{'
		//        'power' power=INT
		//        'type' type=MemoryType
		//        'capacity' capacity=INT
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'memory' name=ID '{'
		//    'power' power=INT
		//    'type' type=MemoryType
		//    'capacity' capacity=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'memory'
		public Keyword getMemoryKeyword_0() { return cMemoryKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'power'
		public Keyword getPowerKeyword_3() { return cPowerKeyword_3; }
		
		//power=INT
		public Assignment getPowerAssignment_4() { return cPowerAssignment_4; }
		
		//INT
		public RuleCall getPowerINTTerminalRuleCall_4_0() { return cPowerINTTerminalRuleCall_4_0; }
		
		//'type'
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }
		
		//type=MemoryType
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }
		
		//MemoryType
		public RuleCall getTypeMemoryTypeEnumRuleCall_6_0() { return cTypeMemoryTypeEnumRuleCall_6_0; }
		
		//'capacity'
		public Keyword getCapacityKeyword_7() { return cCapacityKeyword_7; }
		
		//capacity=INT
		public Assignment getCapacityAssignment_8() { return cCapacityAssignment_8; }
		
		//INT
		public RuleCall getCapacityINTTerminalRuleCall_8_0() { return cCapacityINTTerminalRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class StorageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Storage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStorageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPowerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPowerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPowerINTTerminalRuleCall_4_0 = (RuleCall)cPowerAssignment_4.eContents().get(0);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeStorageTypeEnumRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Keyword cCapacityKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cCapacityAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cCapacityINTTerminalRuleCall_8_0 = (RuleCall)cCapacityAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Storage:
		//    'storage' name=ID '{'
		//        'power' power=INT
		//        'type' type=StorageType
		//        'capacity' capacity=INT
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'storage' name=ID '{'
		//    'power' power=INT
		//    'type' type=StorageType
		//    'capacity' capacity=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'storage'
		public Keyword getStorageKeyword_0() { return cStorageKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'power'
		public Keyword getPowerKeyword_3() { return cPowerKeyword_3; }
		
		//power=INT
		public Assignment getPowerAssignment_4() { return cPowerAssignment_4; }
		
		//INT
		public RuleCall getPowerINTTerminalRuleCall_4_0() { return cPowerINTTerminalRuleCall_4_0; }
		
		//'type'
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }
		
		//type=StorageType
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }
		
		//StorageType
		public RuleCall getTypeStorageTypeEnumRuleCall_6_0() { return cTypeStorageTypeEnumRuleCall_6_0; }
		
		//'capacity'
		public Keyword getCapacityKeyword_7() { return cCapacityKeyword_7; }
		
		//capacity=INT
		public Assignment getCapacityAssignment_8() { return cCapacityAssignment_8; }
		
		//INT
		public RuleCall getCapacityINTTerminalRuleCall_8_0() { return cCapacityINTTerminalRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class DriveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Drive");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDriveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPowerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPowerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPowerINTTerminalRuleCall_4_0 = (RuleCall)cPowerAssignment_4.eContents().get(0);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeDriveTypeEnumRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Drive:
		//    'drive' name=ID '{'
		//        'power' power=INT
		//        'type' type=DriveType
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'drive' name=ID '{'
		//    'power' power=INT
		//    'type' type=DriveType
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'drive'
		public Keyword getDriveKeyword_0() { return cDriveKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'power'
		public Keyword getPowerKeyword_3() { return cPowerKeyword_3; }
		
		//power=INT
		public Assignment getPowerAssignment_4() { return cPowerAssignment_4; }
		
		//INT
		public RuleCall getPowerINTTerminalRuleCall_4_0() { return cPowerINTTerminalRuleCall_4_0; }
		
		//'type'
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }
		
		//type=DriveType
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }
		
		//DriveType
		public RuleCall getTypeDriveTypeEnumRuleCall_6_0() { return cTypeDriveTypeEnumRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class PeripheralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Peripheral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cKindAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cKindPeripheralKindEnumRuleCall_0_0 = (RuleCall)cKindAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPowerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPowerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPowerINTTerminalRuleCall_4_0 = (RuleCall)cPowerAssignment_4.eContents().get(0);
		private final Keyword cPortKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPortAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPortPortEnumRuleCall_6_0 = (RuleCall)cPortAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//// Monitor, Keyboard, Mouse and Printer only differ by kind, so they share one rule
		//Peripheral:
		//    kind=PeripheralKind name=ID '{'
		//        'power' power=INT
		//        'port' port=Port
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//kind=PeripheralKind name=ID '{'
		//    'power' power=INT
		//    'port' port=Port
		//'}'
		public Group getGroup() { return cGroup; }
		
		//kind=PeripheralKind
		public Assignment getKindAssignment_0() { return cKindAssignment_0; }
		
		//PeripheralKind
		public RuleCall getKindPeripheralKindEnumRuleCall_0_0() { return cKindPeripheralKindEnumRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'power'
		public Keyword getPowerKeyword_3() { return cPowerKeyword_3; }
		
		//power=INT
		public Assignment getPowerAssignment_4() { return cPowerAssignment_4; }
		
		//INT
		public RuleCall getPowerINTTerminalRuleCall_4_0() { return cPowerINTTerminalRuleCall_4_0; }
		
		//'port'
		public Keyword getPortKeyword_5() { return cPortKeyword_5; }
		
		//port=Port
		public Assignment getPortAssignment_6() { return cPortAssignment_6; }
		
		//Port
		public RuleCall getPortPortEnumRuleCall_6_0() { return cPortPortEnumRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class PowerSupplyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.PowerSupply");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPsuKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCapacityKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCapacityAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCapacityINTTerminalRuleCall_4_0 = (RuleCall)cCapacityAssignment_4.eContents().get(0);
		private final Keyword cRatingKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRatingAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRatingRatingEnumRuleCall_6_0 = (RuleCall)cRatingAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//PowerSupply:
		//    'psu' name=ID '{'
		//        'capacity' capacity=INT
		//        'rating' rating=Rating
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'psu' name=ID '{'
		//    'capacity' capacity=INT
		//    'rating' rating=Rating
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'psu'
		public Keyword getPsuKeyword_0() { return cPsuKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'capacity'
		public Keyword getCapacityKeyword_3() { return cCapacityKeyword_3; }
		
		//capacity=INT
		public Assignment getCapacityAssignment_4() { return cCapacityAssignment_4; }
		
		//INT
		public RuleCall getCapacityINTTerminalRuleCall_4_0() { return cCapacityINTTerminalRuleCall_4_0; }
		
		//'rating'
		public Keyword getRatingKeyword_5() { return cRatingKeyword_5; }
		
		//rating=Rating
		public Assignment getRatingAssignment_6() { return cRatingAssignment_6; }
		
		//Rating
		public RuleCall getRatingRatingEnumRuleCall_6_0() { return cRatingRatingEnumRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	public class PeripheralKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.PeripheralKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMONITOREnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMONITORMonitorKeyword_0_0 = (Keyword)cMONITOREnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cKEYBOARDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cKEYBOARDKeyboardKeyword_1_0 = (Keyword)cKEYBOARDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMOUSEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMOUSEMouseKeyword_2_0 = (Keyword)cMOUSEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cPRINTEREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cPRINTERPrinterKeyword_3_0 = (Keyword)cPRINTEREnumLiteralDeclaration_3.eContents().get(0);
		
		//enum PeripheralKind:
		//    MONITOR='monitor' | KEYBOARD='keyboard' | MOUSE='mouse' | PRINTER='printer';
		public EnumRule getRule() { return rule; }
		
		//MONITOR='monitor' | KEYBOARD='keyboard' | MOUSE='mouse' | PRINTER='printer'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MONITOR='monitor'
		public EnumLiteralDeclaration getMONITOREnumLiteralDeclaration_0() { return cMONITOREnumLiteralDeclaration_0; }
		
		//'monitor'
		public Keyword getMONITORMonitorKeyword_0_0() { return cMONITORMonitorKeyword_0_0; }
		
		//KEYBOARD='keyboard'
		public EnumLiteralDeclaration getKEYBOARDEnumLiteralDeclaration_1() { return cKEYBOARDEnumLiteralDeclaration_1; }
		
		//'keyboard'
		public Keyword getKEYBOARDKeyboardKeyword_1_0() { return cKEYBOARDKeyboardKeyword_1_0; }
		
		//MOUSE='mouse'
		public EnumLiteralDeclaration getMOUSEEnumLiteralDeclaration_2() { return cMOUSEEnumLiteralDeclaration_2; }
		
		//'mouse'
		public Keyword getMOUSEMouseKeyword_2_0() { return cMOUSEMouseKeyword_2_0; }
		
		//PRINTER='printer'
		public EnumLiteralDeclaration getPRINTEREnumLiteralDeclaration_3() { return cPRINTEREnumLiteralDeclaration_3; }
		
		//'printer'
		public Keyword getPRINTERPrinterKeyword_3_0() { return cPRINTERPrinterKeyword_3_0; }
	}
	public class MotherboardTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.MotherboardType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cATXEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cATXATXKeyword_0_0 = (Keyword)cATXEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMicroATXEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMicroATXMicroATXKeyword_1_0 = (Keyword)cMicroATXEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cMiniITXEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cMiniITXMiniITXKeyword_2_0 = (Keyword)cMiniITXEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum MotherboardType:
		//    ATX | MicroATX | MiniITX;
		public EnumRule getRule() { return rule; }
		
		//ATX | MicroATX | MiniITX
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ATX
		public EnumLiteralDeclaration getATXEnumLiteralDeclaration_0() { return cATXEnumLiteralDeclaration_0; }
		
		public Keyword getATXATXKeyword_0_0() { return cATXATXKeyword_0_0; }
		
		//MicroATX
		public EnumLiteralDeclaration getMicroATXEnumLiteralDeclaration_1() { return cMicroATXEnumLiteralDeclaration_1; }
		
		public Keyword getMicroATXMicroATXKeyword_1_0() { return cMicroATXMicroATXKeyword_1_0; }
		
		//MiniITX
		public EnumLiteralDeclaration getMiniITXEnumLiteralDeclaration_2() { return cMiniITXEnumLiteralDeclaration_2; }
		
		public Keyword getMiniITXMiniITXKeyword_2_0() { return cMiniITXMiniITXKeyword_2_0; }
	}
	public class SocketElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Socket");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAM4EnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAM4AM4Keyword_0_0 = (Keyword)cAM4EnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAM5EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAM5AM5Keyword_1_0 = (Keyword)cAM5EnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLGA1200EnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLGA1200LGA1200Keyword_2_0 = (Keyword)cLGA1200EnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cLGA1700EnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cLGA1700LGA1700Keyword_3_0 = (Keyword)cLGA1700EnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Socket:
		//    AM4 | AM5 | LGA1200 | LGA1700;
		public EnumRule getRule() { return rule; }
		
		//AM4 | AM5 | LGA1200 | LGA1700
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AM4
		public EnumLiteralDeclaration getAM4EnumLiteralDeclaration_0() { return cAM4EnumLiteralDeclaration_0; }
		
		public Keyword getAM4AM4Keyword_0_0() { return cAM4AM4Keyword_0_0; }
		
		//AM5
		public EnumLiteralDeclaration getAM5EnumLiteralDeclaration_1() { return cAM5EnumLiteralDeclaration_1; }
		
		public Keyword getAM5AM5Keyword_1_0() { return cAM5AM5Keyword_1_0; }
		
		//LGA1200
		public EnumLiteralDeclaration getLGA1200EnumLiteralDeclaration_2() { return cLGA1200EnumLiteralDeclaration_2; }
		
		public Keyword getLGA1200LGA1200Keyword_2_0() { return cLGA1200LGA1200Keyword_2_0; }
		
		//LGA1700
		public EnumLiteralDeclaration getLGA1700EnumLiteralDeclaration_3() { return cLGA1700EnumLiteralDeclaration_3; }
		
		public Keyword getLGA1700LGA1700Keyword_3_0() { return cLGA1700LGA1700Keyword_3_0; }
	}
	public class PortElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Port");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cUSBEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cUSBUSBKeyword_0_0 = (Keyword)cUSBEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPS2EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPS2PS2Keyword_1_0 = (Keyword)cPS2EnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cHDMIEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cHDMIHDMIKeyword_2_0 = (Keyword)cHDMIEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDisplayPortEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDisplayPortDisplayPortKeyword_3_0 = (Keyword)cDisplayPortEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cVGAEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cVGAVGAKeyword_4_0 = (Keyword)cVGAEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cEthernetEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cEthernetEthernetKeyword_5_0 = (Keyword)cEthernetEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cAudioEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cAudioAudioKeyword_6_0 = (Keyword)cAudioEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum Port:
		//    USB | PS2 | HDMI | DisplayPort | VGA | Ethernet | Audio;
		public EnumRule getRule() { return rule; }
		
		//USB | PS2 | HDMI | DisplayPort | VGA | Ethernet | Audio
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//USB
		public EnumLiteralDeclaration getUSBEnumLiteralDeclaration_0() { return cUSBEnumLiteralDeclaration_0; }
		
		public Keyword getUSBUSBKeyword_0_0() { return cUSBUSBKeyword_0_0; }
		
		//PS2
		public EnumLiteralDeclaration getPS2EnumLiteralDeclaration_1() { return cPS2EnumLiteralDeclaration_1; }
		
		public Keyword getPS2PS2Keyword_1_0() { return cPS2PS2Keyword_1_0; }
		
		//HDMI
		public EnumLiteralDeclaration getHDMIEnumLiteralDeclaration_2() { return cHDMIEnumLiteralDeclaration_2; }
		
		public Keyword getHDMIHDMIKeyword_2_0() { return cHDMIHDMIKeyword_2_0; }
		
		//DisplayPort
		public EnumLiteralDeclaration getDisplayPortEnumLiteralDeclaration_3() { return cDisplayPortEnumLiteralDeclaration_3; }
		
		public Keyword getDisplayPortDisplayPortKeyword_3_0() { return cDisplayPortDisplayPortKeyword_3_0; }
		
		//VGA
		public EnumLiteralDeclaration getVGAEnumLiteralDeclaration_4() { return cVGAEnumLiteralDeclaration_4; }
		
		public Keyword getVGAVGAKeyword_4_0() { return cVGAVGAKeyword_4_0; }
		
		//Ethernet
		public EnumLiteralDeclaration getEthernetEnumLiteralDeclaration_5() { return cEthernetEnumLiteralDeclaration_5; }
		
		public Keyword getEthernetEthernetKeyword_5_0() { return cEthernetEthernetKeyword_5_0; }
		
		//Audio
		public EnumLiteralDeclaration getAudioEnumLiteralDeclaration_6() { return cAudioEnumLiteralDeclaration_6; }
		
		public Keyword getAudioAudioKeyword_6_0() { return cAudioAudioKeyword_6_0; }
	}
	public class MemoryTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.MemoryType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDDR4EnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDDR4DDR4Keyword_0_0 = (Keyword)cDDR4EnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDDR5EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDDR5DDR5Keyword_1_0 = (Keyword)cDDR5EnumLiteralDeclaration_1.eContents().get(0);
		
		//enum MemoryType:
		//    DDR4 | DDR5;
		public EnumRule getRule() { return rule; }
		
		//DDR4 | DDR5
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DDR4
		public EnumLiteralDeclaration getDDR4EnumLiteralDeclaration_0() { return cDDR4EnumLiteralDeclaration_0; }
		
		public Keyword getDDR4DDR4Keyword_0_0() { return cDDR4DDR4Keyword_0_0; }
		
		//DDR5
		public EnumLiteralDeclaration getDDR5EnumLiteralDeclaration_1() { return cDDR5EnumLiteralDeclaration_1; }
		
		public Keyword getDDR5DDR5Keyword_1_0() { return cDDR5DDR5Keyword_1_0; }
	}
	public class StorageTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.StorageType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cHDDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cHDDHDDKeyword_0_0 = (Keyword)cHDDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSSDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSSDSSDKeyword_1_0 = (Keyword)cSSDEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum StorageType:
		//    HDD | SSD;
		public EnumRule getRule() { return rule; }
		
		//HDD | SSD
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//HDD
		public EnumLiteralDeclaration getHDDEnumLiteralDeclaration_0() { return cHDDEnumLiteralDeclaration_0; }
		
		public Keyword getHDDHDDKeyword_0_0() { return cHDDHDDKeyword_0_0; }
		
		//SSD
		public EnumLiteralDeclaration getSSDEnumLiteralDeclaration_1() { return cSSDEnumLiteralDeclaration_1; }
		
		public Keyword getSSDSSDKeyword_1_0() { return cSSDSSDKeyword_1_0; }
	}
	public class DriveTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.DriveType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCD_ROMEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCD_ROMCD_ROMKeyword_0_0 = (Keyword)cCD_ROMEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCD_REnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCD_RCD_RKeyword_1_0 = (Keyword)cCD_REnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCD_RWEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCD_RWCD_RWKeyword_2_0 = (Keyword)cCD_RWEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDVD_ROMEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDVD_ROMDVD_ROMKeyword_3_0 = (Keyword)cDVD_ROMEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cBluRayEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cBluRayBluRayKeyword_4_0 = (Keyword)cBluRayEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum DriveType:
		//    CD_ROM | CD_R | CD_RW | DVD_ROM | BluRay;
		public EnumRule getRule() { return rule; }
		
		//CD_ROM | CD_R | CD_RW | DVD_ROM | BluRay
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CD_ROM
		public EnumLiteralDeclaration getCD_ROMEnumLiteralDeclaration_0() { return cCD_ROMEnumLiteralDeclaration_0; }
		
		public Keyword getCD_ROMCD_ROMKeyword_0_0() { return cCD_ROMCD_ROMKeyword_0_0; }
		
		//CD_R
		public EnumLiteralDeclaration getCD_REnumLiteralDeclaration_1() { return cCD_REnumLiteralDeclaration_1; }
		
		public Keyword getCD_RCD_RKeyword_1_0() { return cCD_RCD_RKeyword_1_0; }
		
		//CD_RW
		public EnumLiteralDeclaration getCD_RWEnumLiteralDeclaration_2() { return cCD_RWEnumLiteralDeclaration_2; }
		
		public Keyword getCD_RWCD_RWKeyword_2_0() { return cCD_RWCD_RWKeyword_2_0; }
		
		//DVD_ROM
		public EnumLiteralDeclaration getDVD_ROMEnumLiteralDeclaration_3() { return cDVD_ROMEnumLiteralDeclaration_3; }
		
		public Keyword getDVD_ROMDVD_ROMKeyword_3_0() { return cDVD_ROMDVD_ROMKeyword_3_0; }
		
		//BluRay
		public EnumLiteralDeclaration getBluRayEnumLiteralDeclaration_4() { return cBluRayEnumLiteralDeclaration_4; }
		
		public Keyword getBluRayBluRayKeyword_4_0() { return cBluRayBluRayKeyword_4_0; }
	}
	public class RatingElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.computer.ComputerDsl.Rating");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBronzeEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBronzeBronzeKeyword_0_0 = (Keyword)cBronzeEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSilverEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSilverSilverKeyword_1_0 = (Keyword)cSilverEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cGoldEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cGoldGoldKeyword_2_0 = (Keyword)cGoldEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cPlatinumEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cPlatinumPlatinumKeyword_3_0 = (Keyword)cPlatinumEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cTitaniumEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cTitaniumTitaniumKeyword_4_0 = (Keyword)cTitaniumEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Rating:
		//    Bronze | Silver | Gold | Platinum | Titanium;
		public EnumRule getRule() { return rule; }
		
		//Bronze | Silver | Gold | Platinum | Titanium
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Bronze
		public EnumLiteralDeclaration getBronzeEnumLiteralDeclaration_0() { return cBronzeEnumLiteralDeclaration_0; }
		
		public Keyword getBronzeBronzeKeyword_0_0() { return cBronzeBronzeKeyword_0_0; }
		
		//Silver
		public EnumLiteralDeclaration getSilverEnumLiteralDeclaration_1() { return cSilverEnumLiteralDeclaration_1; }
		
		public Keyword getSilverSilverKeyword_1_0() { return cSilverSilverKeyword_1_0; }
		
		//Gold
		public EnumLiteralDeclaration getGoldEnumLiteralDeclaration_2() { return cGoldEnumLiteralDeclaration_2; }
		
		public Keyword getGoldGoldKeyword_2_0() { return cGoldGoldKeyword_2_0; }
		
		//Platinum
		public EnumLiteralDeclaration getPlatinumEnumLiteralDeclaration_3() { return cPlatinumEnumLiteralDeclaration_3; }
		
		public Keyword getPlatinumPlatinumKeyword_3_0() { return cPlatinumPlatinumKeyword_3_0; }
		
		//Titanium
		public EnumLiteralDeclaration getTitaniumEnumLiteralDeclaration_4() { return cTitaniumEnumLiteralDeclaration_4; }
		
		public Keyword getTitaniumTitaniumKeyword_4_0() { return cTitaniumTitaniumKeyword_4_0; }
	}
	
	private final ModelElements pModel;
	private final AbstractElementElements pAbstractElement;
	private final PackageDeclarationElements pPackageDeclaration;
	private final ImportElements pImport;
	private final QualifiedNameElements pQualifiedName;
	private final QualifiedNameWithWildcardElements pQualifiedNameWithWildcard;
	private final ComputerElements pComputer;
	private final PartElements pPart;
	private final MotherboardElements pMotherboard;
	private final ProcessorElements pProcessor;
	private final GraphicsCardElements pGraphicsCard;
	private final MemoryElements pMemory;
	private final StorageElements pStorage;
	private final DriveElements pDrive;
	private final PeripheralElements pPeripheral;
	private final PowerSupplyElements pPowerSupply;
	private final PeripheralKindElements ePeripheralKind;
	private final MotherboardTypeElements eMotherboardType;
	private final SocketElements eSocket;
	private final PortElements ePort;
	private final MemoryTypeElements eMemoryType;
	private final StorageTypeElements eStorageType;
	private final DriveTypeElements eDriveType;
	private final RatingElements eRating;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ComputerDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pAbstractElement = new AbstractElementElements();
		this.pPackageDeclaration = new PackageDeclarationElements();
		this.pImport = new ImportElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pQualifiedNameWithWildcard = new QualifiedNameWithWildcardElements();
		this.pComputer = new ComputerElements();
		this.pPart = new PartElements();
		this.pMotherboard = new MotherboardElements();
		this.pProcessor = new ProcessorElements();
		this.pGraphicsCard = new GraphicsCardElements();
		this.pMemory = new MemoryElements();
		this.pStorage = new StorageElements();
		this.pDrive = new DriveElements();
		this.pPeripheral = new PeripheralElements();
		this.pPowerSupply = new PowerSupplyElements();
		this.ePeripheralKind = new PeripheralKindElements();
		this.eMotherboardType = new MotherboardTypeElements();
		this.eSocket = new SocketElements();
		this.ePort = new PortElements();
		this.eMemoryType = new MemoryTypeElements();
		this.eStorageType = new StorageTypeElements();
		this.eDriveType = new DriveTypeElements();
		this.eRating = new RatingElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.computer.ComputerDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    (elements+=AbstractElement)*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//AbstractElement:
	//    PackageDeclaration | Import | Part | Computer;
	public AbstractElementElements getAbstractElementAccess() {
		return pAbstractElement;
	}
	
	public ParserRule getAbstractElementRule() {
		return getAbstractElementAccess().getRule();
	}
	
	//PackageDeclaration:
	//    'package' name=QualifiedName '{'
	//        (elements+=AbstractElement)*
	//    '}';
	public PackageDeclarationElements getPackageDeclarationAccess() {
		return pPackageDeclaration;
	}
	
	public ParserRule getPackageDeclarationRule() {
		return getPackageDeclarationAccess().getRule();
	}
	
	//Import:
	//    'import' importedNamespace=QualifiedNameWithWildcard;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}
	
	//QualifiedName:
	//    ID ('.' ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//QualifiedNameWithWildcard:
	//    QualifiedName '.*'?;
	public QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return pQualifiedNameWithWildcard;
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}
	
	//// A computer only references parts; the parts can live in other packages or files.
	//Computer:
	//    'computer' name=ID '{'
	//        'motherboard' motherboard=[Motherboard|QualifiedName]
	//        'processor' processor=[Processor|QualifiedName]
	//        ('graphics' graphicsCard=[GraphicsCard|QualifiedName])?
	//        'memory' memory+=[Memory|QualifiedName] (',' memory+=[Memory|QualifiedName])*
	//        'storage' storage+=[Storage|QualifiedName] (',' storage+=[Storage|QualifiedName])*
	//        ('drive' drive=[Drive|QualifiedName])?
	//        ('peripherals' peripherals+=[Peripheral|QualifiedName] (',' peripherals+=[Peripheral|QualifiedName])*)?
	//        'psu' powerSupply=[PowerSupply|QualifiedName]
	//    '}';
	public ComputerElements getComputerAccess() {
		return pComputer;
	}
	
	public ParserRule getComputerRule() {
		return getComputerAccess().getRule();
	}
	
	//Part:
	//    Motherboard | Processor | GraphicsCard | Memory | Storage | Drive | Peripheral | PowerSupply;
	public PartElements getPartAccess() {
		return pPart;
	}
	
	public ParserRule getPartRule() {
		return getPartAccess().getRule();
	}
	
	//// power is in watts, vram and capacity of memory/storage in GB
	//Motherboard:
	//    'motherboard' name=ID '{'
	//        'power' power=INT
	//        'type' type=MotherboardType
	//        'chipset' chipset=STRING
	//        'socket' socket=Socket
	//        ('ports' ports+=Port (',' ports+=Port)*)?
	//    '}';
	public MotherboardElements getMotherboardAccess() {
		return pMotherboard;
	}
	
	public ParserRule getMotherboardRule() {
		return getMotherboardAccess().getRule();
	}
	
	//Processor:
	//    'processor' name=ID '{'
	//        'power' power=INT
	//        ('model' model=STRING)?
	//        'socket' socket=Socket
	//        'cores' cores=INT
	//    '}';
	public ProcessorElements getProcessorAccess() {
		return pProcessor;
	}
	
	public ParserRule getProcessorRule() {
		return getProcessorAccess().getRule();
	}
	
	//GraphicsCard:
	//    'graphics' name=ID '{'
	//        'power' power=INT
	//        ('model' model=STRING)?
	//        'vram' vram=INT
	//    '}';
	public GraphicsCardElements getGraphicsCardAccess() {
		return pGraphicsCard;
	}
	
	public ParserRule getGraphicsCardRule() {
		return getGraphicsCardAccess().getRule();
	}
	
	//Memory:
	//    'memory' name=ID '{'
	//        'power' power=INT
	//        'type' type=MemoryType
	//        'capacity' capacity=INT
	//    '}';
	public MemoryElements getMemoryAccess() {
		return pMemory;
	}
	
	public ParserRule getMemoryRule() {
		return getMemoryAccess().getRule();
	}
	
	//Storage:
	//    'storage' name=ID '{'
	//        'power' power=INT
	//        'type' type=StorageType
	//        'capacity' capacity=INT
	//    '}';
	public StorageElements getStorageAccess() {
		return pStorage;
	}
	
	public ParserRule getStorageRule() {
		return getStorageAccess().getRule();
	}
	
	//Drive:
	//    'drive' name=ID '{'
	//        'power' power=INT
	//        'type' type=DriveType
	//    '}';
	public DriveElements getDriveAccess() {
		return pDrive;
	}
	
	public ParserRule getDriveRule() {
		return getDriveAccess().getRule();
	}
	
	//// Monitor, Keyboard, Mouse and Printer only differ by kind, so they share one rule
	//Peripheral:
	//    kind=PeripheralKind name=ID '{'
	//        'power' power=INT
	//        'port' port=Port
	//    '}';
	public PeripheralElements getPeripheralAccess() {
		return pPeripheral;
	}
	
	public ParserRule getPeripheralRule() {
		return getPeripheralAccess().getRule();
	}
	
	//PowerSupply:
	//    'psu' name=ID '{'
	//        'capacity' capacity=INT
	//        'rating' rating=Rating
	//    '}';
	public PowerSupplyElements getPowerSupplyAccess() {
		return pPowerSupply;
	}
	
	public ParserRule getPowerSupplyRule() {
		return getPowerSupplyAccess().getRule();
	}
	
	//enum PeripheralKind:
	//    MONITOR='monitor' | KEYBOARD='keyboard' | MOUSE='mouse' | PRINTER='printer';
	public PeripheralKindElements getPeripheralKindAccess() {
		return ePeripheralKind;
	}
	
	public EnumRule getPeripheralKindRule() {
		return getPeripheralKindAccess().getRule();
	}
	
	//enum MotherboardType:
	//    ATX | MicroATX | MiniITX;
	public MotherboardTypeElements getMotherboardTypeAccess() {
		return eMotherboardType;
	}
	
	public EnumRule getMotherboardTypeRule() {
		return getMotherboardTypeAccess().getRule();
	}
	
	//enum Socket:
	//    AM4 | AM5 | LGA1200 | LGA1700;
	public SocketElements getSocketAccess() {
		return eSocket;
	}
	
	public EnumRule getSocketRule() {
		return getSocketAccess().getRule();
	}
	
	//enum Port:
	//    USB | PS2 | HDMI | DisplayPort | VGA | Ethernet | Audio;
	public PortElements getPortAccess() {
		return ePort;
	}
	
	public EnumRule getPortRule() {
		return getPortAccess().getRule();
	}
	
	//enum MemoryType:
	//    DDR4 | DDR5;
	public MemoryTypeElements getMemoryTypeAccess() {
		return eMemoryType;
	}
	
	public EnumRule getMemoryTypeRule() {
		return getMemoryTypeAccess().getRule();
	}
	
	//enum StorageType:
	//    HDD | SSD;
	public StorageTypeElements getStorageTypeAccess() {
		return eStorageType;
	}
	
	public EnumRule getStorageTypeRule() {
		return getStorageTypeAccess().getRule();
	}
	
	//enum DriveType:
	//    CD_ROM | CD_R | CD_RW | DVD_ROM | BluRay;
	public DriveTypeElements getDriveTypeAccess() {
		return eDriveType;
	}
	
	public EnumRule getDriveTypeRule() {
		return getDriveTypeAccess().getRule();
	}
	
	//enum Rating:
	//    Bronze | Silver | Gold | Platinum | Titanium;
	public RatingElements getRatingAccess() {
		return eRating;
	}
	
	public EnumRule getRatingRule() {
		return getRatingAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
