/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ComputerDslRuntimeModule extends AbstractComputerDslRuntimeModule {
}
