/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractComputerDslScopeProvider extends DelegatingScopeProvider {
}
