/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ComputerDslUiModule extends AbstractComputerDslUiModule {

	public ComputerDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
