/*
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.computer.parser.antlr.internal.InternalComputerDslParser;
import org.xtext.example.computer.services.ComputerDslGrammarAccess;

public class ComputerDslParser extends AbstractAntlrParser {

	@Inject
	private ComputerDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalComputerDslParser createParser(XtextTokenStream stream) {
		return new InternalComputerDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ComputerDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ComputerDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
