#

pluginName = practice1 Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Query_type = Query
_UI_Select_type = Select
_UI_Union_type = Union
_UI_Selection_type = Selection
_UI_TableReference_type = Table Reference
_UI_Condition_type = Condition
_UI_ColumnSelection_type = Column Selection
_UI_AllColumnsSelection_type = All Columns Selection
_UI_Comparison_type = Comparison
_UI_AND_type = AND
_UI_OR_type = OR
_UI_NOT_type = NOT
_UI_EXIST_type = EXIST
_UI_Value_type = Value
_UI_AttributeReference_type = Attribute Reference
_UI_Literal_type = Literal
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Select_selections_feature = Selections
_UI_Select_tables_feature = Tables
_UI_Select_condition_feature = Condition
_UI_Union_left_feature = Left
_UI_Union_right_feature = Right
_UI_TableReference_name_feature = Name
_UI_TableReference_alias_feature = Alias
_UI_ColumnSelection_attribute_feature = Attribute
_UI_ColumnSelection_alias_feature = Alias
_UI_ColumnSelection_table_feature = Table
_UI_AllColumnsSelection_table_feature = Table
_UI_Comparison_left_feature = Left
_UI_Comparison_right_feature = Right
_UI_Comparison_operator_feature = Operator
_UI_AND_left_feature = Left
_UI_AND_right_feature = Right
_UI_OR_left_feature = Left
_UI_OR_right_feature = Right
_UI_NOT_condition_feature = Condition
_UI_EXIST_query_feature = Query
_UI_AttributeReference_attribute_feature = Attribute
_UI_AttributeReference_table_feature = Table
_UI_Literal_value_feature = Value
_UI_Unknown_feature = Unspecified

_UI_ComparisonOp_EQUAL_literal = EQUAL
_UI_ComparisonOp_LESS_literal = LESS
_UI_ComparisonOp_GREATER_literal = GREATER
_UI_ComparisonOp_NOT_EQUAL_literal = NOT_EQUAL
