/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.example.computer.computerDsl.Computer;
import org.xtext.example.computer.computerDsl.ComputerDslPackage;
import org.xtext.example.computer.computerDsl.Drive;
import org.xtext.example.computer.computerDsl.GraphicsCard;
import org.xtext.example.computer.computerDsl.Memory;
import org.xtext.example.computer.computerDsl.Motherboard;
import org.xtext.example.computer.computerDsl.Peripheral;
import org.xtext.example.computer.computerDsl.PowerSupply;
import org.xtext.example.computer.computerDsl.Processor;
import org.xtext.example.computer.computerDsl.Storage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Computer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl#getMotherboard <em>Motherboard</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl#getProcessor <em>Processor</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl#getGraphicsCard <em>Graphics Card</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl#getMemory <em>Memory</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl#getStorage <em>Storage</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl#getDrive <em>Drive</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl#getPeripherals <em>Peripherals</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ComputerImpl#getPowerSupply <em>Power Supply</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComputerImpl extends AbstractElementImpl implements Computer
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getMotherboard() <em>Motherboard</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMotherboard()
   * @generated
   * @ordered
   */
  protected Motherboard motherboard;

  /**
   * The cached value of the '{@link #getProcessor() <em>Processor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProcessor()
   * @generated
   * @ordered
   */
  protected Processor processor;

  /**
   * The cached value of the '{@link #getGraphicsCard() <em>Graphics Card</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGraphicsCard()
   * @generated
   * @ordered
   */
  protected GraphicsCard graphicsCard;

  /**
   * The cached value of the '{@link #getMemory() <em>Memory</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMemory()
   * @generated
   * @ordered
   */
  protected EList<Memory> memory;

  /**
   * The cached value of the '{@link #getStorage() <em>Storage</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStorage()
   * @generated
   * @ordered
   */
  protected EList<Storage> storage;

  /**
   * The cached value of the '{@link #getDrive() <em>Drive</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDrive()
   * @generated
   * @ordered
   */
  protected Drive drive;

  /**
   * The cached value of the '{@link #getPeripherals() <em>Peripherals</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPeripherals()
   * @generated
   * @ordered
   */
  protected EList<Peripheral> peripherals;

  /**
   * The cached value of the '{@link #getPowerSupply() <em>Power Supply</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPowerSupply()
   * @generated
   * @ordered
   */
  protected PowerSupply powerSupply;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComputerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComputerDslPackage.Literals.COMPUTER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.COMPUTER__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Motherboard getMotherboard()
  {
    if (motherboard != null && motherboard.eIsProxy())
    {
      InternalEObject oldMotherboard = (InternalEObject)motherboard;
      motherboard = (Motherboard)eResolveProxy(oldMotherboard);
      if (motherboard != oldMotherboard)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComputerDslPackage.COMPUTER__MOTHERBOARD, oldMotherboard, motherboard));
      }
    }
    return motherboard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Motherboard basicGetMotherboard()
  {
    return motherboard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMotherboard(Motherboard newMotherboard)
  {
    Motherboard oldMotherboard = motherboard;
    motherboard = newMotherboard;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.COMPUTER__MOTHERBOARD, oldMotherboard, motherboard));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Processor getProcessor()
  {
    if (processor != null && processor.eIsProxy())
    {
      InternalEObject oldProcessor = (InternalEObject)processor;
      processor = (Processor)eResolveProxy(oldProcessor);
      if (processor != oldProcessor)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComputerDslPackage.COMPUTER__PROCESSOR, oldProcessor, processor));
      }
    }
    return processor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Processor basicGetProcessor()
  {
    return processor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProcessor(Processor newProcessor)
  {
    Processor oldProcessor = processor;
    processor = newProcessor;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.COMPUTER__PROCESSOR, oldProcessor, processor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GraphicsCard getGraphicsCard()
  {
    if (graphicsCard != null && graphicsCard.eIsProxy())
    {
      InternalEObject oldGraphicsCard = (InternalEObject)graphicsCard;
      graphicsCard = (GraphicsCard)eResolveProxy(oldGraphicsCard);
      if (graphicsCard != oldGraphicsCard)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComputerDslPackage.COMPUTER__GRAPHICS_CARD, oldGraphicsCard, graphicsCard));
      }
    }
    return graphicsCard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphicsCard basicGetGraphicsCard()
  {
    return graphicsCard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGraphicsCard(GraphicsCard newGraphicsCard)
  {
    GraphicsCard oldGraphicsCard = graphicsCard;
    graphicsCard = newGraphicsCard;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.COMPUTER__GRAPHICS_CARD, oldGraphicsCard, graphicsCard));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Memory> getMemory()
  {
    if (memory == null)
    {
      memory = new EObjectResolvingEList<Memory>(Memory.class, this, ComputerDslPackage.COMPUTER__MEMORY);
    }
    return memory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Storage> getStorage()
  {
    if (storage == null)
    {
      storage = new EObjectResolvingEList<Storage>(Storage.class, this, ComputerDslPackage.COMPUTER__STORAGE);
    }
    return storage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Drive getDrive()
  {
    if (drive != null && drive.eIsProxy())
    {
      InternalEObject oldDrive = (InternalEObject)drive;
      drive = (Drive)eResolveProxy(oldDrive);
      if (drive != oldDrive)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComputerDslPackage.COMPUTER__DRIVE, oldDrive, drive));
      }
    }
    return drive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Drive basicGetDrive()
  {
    return drive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDrive(Drive newDrive)
  {
    Drive oldDrive = drive;
    drive = newDrive;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.COMPUTER__DRIVE, oldDrive, drive));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Peripheral> getPeripherals()
  {
    if (peripherals == null)
    {
      peripherals = new EObjectResolvingEList<Peripheral>(Peripheral.class, this, ComputerDslPackage.COMPUTER__PERIPHERALS);
    }
    return peripherals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PowerSupply getPowerSupply()
  {
    if (powerSupply != null && powerSupply.eIsProxy())
    {
      InternalEObject oldPowerSupply = (InternalEObject)powerSupply;
      powerSupply = (PowerSupply)eResolveProxy(oldPowerSupply);
      if (powerSupply != oldPowerSupply)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ComputerDslPackage.COMPUTER__POWER_SUPPLY, oldPowerSupply, powerSupply));
      }
    }
    return powerSupply;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PowerSupply basicGetPowerSupply()
  {
    return powerSupply;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPowerSupply(PowerSupply newPowerSupply)
  {
    PowerSupply oldPowerSupply = powerSupply;
    powerSupply = newPowerSupply;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.COMPUTER__POWER_SUPPLY, oldPowerSupply, powerSupply));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComputerDslPackage.COMPUTER__NAME:
        return getName();
      case ComputerDslPackage.COMPUTER__MOTHERBOARD:
        if (resolve) return getMotherboard();
        return basicGetMotherboard();
      case ComputerDslPackage.COMPUTER__PROCESSOR:
        if (resolve) return getProcessor();
        return basicGetProcessor();
      case ComputerDslPackage.COMPUTER__GRAPHICS_CARD:
        if (resolve) return getGraphicsCard();
        return basicGetGraphicsCard();
      case ComputerDslPackage.COMPUTER__MEMORY:
        return getMemory();
      case ComputerDslPackage.COMPUTER__STORAGE:
        return getStorage();
      case ComputerDslPackage.COMPUTER__DRIVE:
        if (resolve) return getDrive();
        return basicGetDrive();
      case ComputerDslPackage.COMPUTER__PERIPHERALS:
        return getPeripherals();
      case ComputerDslPackage.COMPUTER__POWER_SUPPLY:
        if (resolve) return getPowerSupply();
        return basicGetPowerSupply();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComputerDslPackage.COMPUTER__NAME:
        setName((String)newValue);
        return;
      case ComputerDslPackage.COMPUTER__MOTHERBOARD:
        setMotherboard((Motherboard)newValue);
        return;
      case ComputerDslPackage.COMPUTER__PROCESSOR:
        setProcessor((Processor)newValue);
        return;
      case ComputerDslPackage.COMPUTER__GRAPHICS_CARD:
        setGraphicsCard((GraphicsCard)newValue);
        return;
      case ComputerDslPackage.COMPUTER__MEMORY:
        getMemory().clear();
        getMemory().addAll((Collection<? extends Memory>)newValue);
        return;
      case ComputerDslPackage.COMPUTER__STORAGE:
        getStorage().clear();
        getStorage().addAll((Collection<? extends Storage>)newValue);
        return;
      case ComputerDslPackage.COMPUTER__DRIVE:
        setDrive((Drive)newValue);
        return;
      case ComputerDslPackage.COMPUTER__PERIPHERALS:
        getPeripherals().clear();
        getPeripherals().addAll((Collection<? extends Peripheral>)newValue);
        return;
      case ComputerDslPackage.COMPUTER__POWER_SUPPLY:
        setPowerSupply((PowerSupply)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComputerDslPackage.COMPUTER__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ComputerDslPackage.COMPUTER__MOTHERBOARD:
        setMotherboard((Motherboard)null);
        return;
      case ComputerDslPackage.COMPUTER__PROCESSOR:
        setProcessor((Processor)null);
        return;
      case ComputerDslPackage.COMPUTER__GRAPHICS_CARD:
        setGraphicsCard((GraphicsCard)null);
        return;
      case ComputerDslPackage.COMPUTER__MEMORY:
        getMemory().clear();
        return;
      case ComputerDslPackage.COMPUTER__STORAGE:
        getStorage().clear();
        return;
      case ComputerDslPackage.COMPUTER__DRIVE:
        setDrive((Drive)null);
        return;
      case ComputerDslPackage.COMPUTER__PERIPHERALS:
        getPeripherals().clear();
        return;
      case ComputerDslPackage.COMPUTER__POWER_SUPPLY:
        setPowerSupply((PowerSupply)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComputerDslPackage.COMPUTER__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ComputerDslPackage.COMPUTER__MOTHERBOARD:
        return motherboard != null;
      case ComputerDslPackage.COMPUTER__PROCESSOR:
        return processor != null;
      case ComputerDslPackage.COMPUTER__GRAPHICS_CARD:
        return graphicsCard != null;
      case ComputerDslPackage.COMPUTER__MEMORY:
        return memory != null && !memory.isEmpty();
      case ComputerDslPackage.COMPUTER__STORAGE:
        return storage != null && !storage.isEmpty();
      case ComputerDslPackage.COMPUTER__DRIVE:
        return drive != null;
      case ComputerDslPackage.COMPUTER__PERIPHERALS:
        return peripherals != null && !peripherals.isEmpty();
      case ComputerDslPackage.COMPUTER__POWER_SUPPLY:
        return powerSupply != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ComputerImpl
