/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.computer.computerDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ComputerDslFactoryImpl extends EFactoryImpl implements ComputerDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ComputerDslFactory init()
  {
    try
    {
      ComputerDslFactory theComputerDslFactory = (ComputerDslFactory)EPackage.Registry.INSTANCE.getEFactory(ComputerDslPackage.eNS_URI);
      if (theComputerDslFactory != null)
      {
        return theComputerDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ComputerDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComputerDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ComputerDslPackage.MODEL: return createModel();
      case ComputerDslPackage.ABSTRACT_ELEMENT: return createAbstractElement();
      case ComputerDslPackage.PACKAGE_DECLARATION: return createPackageDeclaration();
      case ComputerDslPackage.IMPORT: return createImport();
      case ComputerDslPackage.COMPUTER: return createComputer();
      case ComputerDslPackage.PART: return createPart();
      case ComputerDslPackage.MOTHERBOARD: return createMotherboard();
      case ComputerDslPackage.PROCESSOR: return createProcessor();
      case ComputerDslPackage.GRAPHICS_CARD: return createGraphicsCard();
      case ComputerDslPackage.MEMORY: return createMemory();
      case ComputerDslPackage.STORAGE: return createStorage();
      case ComputerDslPackage.DRIVE: return createDrive();
      case ComputerDslPackage.PERIPHERAL: return createPeripheral();
      case ComputerDslPackage.POWER_SUPPLY: return createPowerSupply();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case ComputerDslPackage.PERIPHERAL_KIND:
        return createPeripheralKindFromString(eDataType, initialValue);
      case ComputerDslPackage.MOTHERBOARD_TYPE:
        return createMotherboardTypeFromString(eDataType, initialValue);
      case ComputerDslPackage.SOCKET:
        return createSocketFromString(eDataType, initialValue);
      case ComputerDslPackage.PORT:
        return createPortFromString(eDataType, initialValue);
      case ComputerDslPackage.MEMORY_TYPE:
        return createMemoryTypeFromString(eDataType, initialValue);
      case ComputerDslPackage.STORAGE_TYPE:
        return createStorageTypeFromString(eDataType, initialValue);
      case ComputerDslPackage.DRIVE_TYPE:
        return createDriveTypeFromString(eDataType, initialValue);
      case ComputerDslPackage.RATING:
        return createRatingFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case ComputerDslPackage.PERIPHERAL_KIND:
        return convertPeripheralKindToString(eDataType, instanceValue);
      case ComputerDslPackage.MOTHERBOARD_TYPE:
        return convertMotherboardTypeToString(eDataType, instanceValue);
      case ComputerDslPackage.SOCKET:
        return convertSocketToString(eDataType, instanceValue);
      case ComputerDslPackage.PORT:
        return convertPortToString(eDataType, instanceValue);
      case ComputerDslPackage.MEMORY_TYPE:
        return convertMemoryTypeToString(eDataType, instanceValue);
      case ComputerDslPackage.STORAGE_TYPE:
        return convertStorageTypeToString(eDataType, instanceValue);
      case ComputerDslPackage.DRIVE_TYPE:
        return convertDriveTypeToString(eDataType, instanceValue);
      case ComputerDslPackage.RATING:
        return convertRatingToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractElement createAbstractElement()
  {
    AbstractElementImpl abstractElement = new AbstractElementImpl();
    return abstractElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PackageDeclaration createPackageDeclaration()
  {
    PackageDeclarationImpl packageDeclaration = new PackageDeclarationImpl();
    return packageDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Computer createComputer()
  {
    ComputerImpl computer = new ComputerImpl();
    return computer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Part createPart()
  {
    PartImpl part = new PartImpl();
    return part;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Motherboard createMotherboard()
  {
    MotherboardImpl motherboard = new MotherboardImpl();
    return motherboard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Processor createProcessor()
  {
    ProcessorImpl processor = new ProcessorImpl();
    return processor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GraphicsCard createGraphicsCard()
  {
    GraphicsCardImpl graphicsCard = new GraphicsCardImpl();
    return graphicsCard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Memory createMemory()
  {
    MemoryImpl memory = new MemoryImpl();
    return memory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Storage createStorage()
  {
    StorageImpl storage = new StorageImpl();
    return storage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Drive createDrive()
  {
    DriveImpl drive = new DriveImpl();
    return drive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Peripheral createPeripheral()
  {
    PeripheralImpl peripheral = new PeripheralImpl();
    return peripheral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PowerSupply createPowerSupply()
  {
    PowerSupplyImpl powerSupply = new PowerSupplyImpl();
    return powerSupply;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PeripheralKind createPeripheralKindFromString(EDataType eDataType, String initialValue)
  {
    PeripheralKind result = PeripheralKind.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertPeripheralKindToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MotherboardType createMotherboardTypeFromString(EDataType eDataType, String initialValue)
  {
    MotherboardType result = MotherboardType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertMotherboardTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Socket createSocketFromString(EDataType eDataType, String initialValue)
  {
    Socket result = Socket.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertSocketToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Port createPortFromString(EDataType eDataType, String initialValue)
  {
    Port result = Port.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertPortToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MemoryType createMemoryTypeFromString(EDataType eDataType, String initialValue)
  {
    MemoryType result = MemoryType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertMemoryTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StorageType createStorageTypeFromString(EDataType eDataType, String initialValue)
  {
    StorageType result = StorageType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertStorageTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DriveType createDriveTypeFromString(EDataType eDataType, String initialValue)
  {
    DriveType result = DriveType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertDriveTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Rating createRatingFromString(EDataType eDataType, String initialValue)
  {
    Rating result = Rating.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertRatingToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComputerDslPackage getComputerDslPackage()
  {
    return (ComputerDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ComputerDslPackage getPackage()
  {
    return ComputerDslPackage.eINSTANCE;
  }

} //ComputerDslFactoryImpl
