/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.computer.computerDsl.AbstractElement;
import org.xtext.example.computer.computerDsl.Computer;
import org.xtext.example.computer.computerDsl.ComputerDslFactory;
import org.xtext.example.computer.computerDsl.ComputerDslPackage;
import org.xtext.example.computer.computerDsl.Drive;
import org.xtext.example.computer.computerDsl.DriveType;
import org.xtext.example.computer.computerDsl.GraphicsCard;
import org.xtext.example.computer.computerDsl.Import;
import org.xtext.example.computer.computerDsl.Memory;
import org.xtext.example.computer.computerDsl.MemoryType;
import org.xtext.example.computer.computerDsl.Model;
import org.xtext.example.computer.computerDsl.Motherboard;
import org.xtext.example.computer.computerDsl.MotherboardType;
import org.xtext.example.computer.computerDsl.PackageDeclaration;
import org.xtext.example.computer.computerDsl.Part;
import org.xtext.example.computer.computerDsl.Peripheral;
import org.xtext.example.computer.computerDsl.PeripheralKind;
import org.xtext.example.computer.computerDsl.Port;
import org.xtext.example.computer.computerDsl.PowerSupply;
import org.xtext.example.computer.computerDsl.Processor;
import org.xtext.example.computer.computerDsl.Rating;
import org.xtext.example.computer.computerDsl.Socket;
import org.xtext.example.computer.computerDsl.Storage;
import org.xtext.example.computer.computerDsl.StorageType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ComputerDslPackageImpl extends EPackageImpl implements ComputerDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass abstractElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass packageDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass importEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass computerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass partEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass motherboardEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass processorEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass graphicsCardEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass memoryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass storageEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass driveEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass peripheralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass powerSupplyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum peripheralKindEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum motherboardTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum socketEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum portEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum memoryTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum storageTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum driveTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum ratingEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.computer.computerDsl.ComputerDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private ComputerDslPackageImpl()
  {
    super(eNS_URI, ComputerDslFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link ComputerDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static ComputerDslPackage init()
  {
    if (isInited) return (ComputerDslPackage)EPackage.Registry.INSTANCE.getEPackage(ComputerDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredComputerDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    ComputerDslPackageImpl theComputerDslPackage = registeredComputerDslPackage instanceof ComputerDslPackageImpl ? (ComputerDslPackageImpl)registeredComputerDslPackage : new ComputerDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theComputerDslPackage.createPackageContents();

    // Initialize created meta-data
    theComputerDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theComputerDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(ComputerDslPackage.eNS_URI, theComputerDslPackage);
    return theComputerDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Elements()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAbstractElement()
  {
    return abstractElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPackageDeclaration()
  {
    return packageDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPackageDeclaration_Name()
  {
    return (EAttribute)packageDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPackageDeclaration_Elements()
  {
    return (EReference)packageDeclarationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImport()
  {
    return importEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImport_ImportedNamespace()
  {
    return (EAttribute)importEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComputer()
  {
    return computerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComputer_Name()
  {
    return (EAttribute)computerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComputer_Motherboard()
  {
    return (EReference)computerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComputer_Processor()
  {
    return (EReference)computerEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComputer_GraphicsCard()
  {
    return (EReference)computerEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComputer_Memory()
  {
    return (EReference)computerEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComputer_Storage()
  {
    return (EReference)computerEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComputer_Drive()
  {
    return (EReference)computerEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComputer_Peripherals()
  {
    return (EReference)computerEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComputer_PowerSupply()
  {
    return (EReference)computerEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPart()
  {
    return partEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPart_Name()
  {
    return (EAttribute)partEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMotherboard()
  {
    return motherboardEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMotherboard_Power()
  {
    return (EAttribute)motherboardEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMotherboard_Type()
  {
    return (EAttribute)motherboardEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMotherboard_Chipset()
  {
    return (EAttribute)motherboardEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMotherboard_Socket()
  {
    return (EAttribute)motherboardEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMotherboard_Ports()
  {
    return (EAttribute)motherboardEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getProcessor()
  {
    return processorEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getProcessor_Power()
  {
    return (EAttribute)processorEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getProcessor_Model()
  {
    return (EAttribute)processorEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getProcessor_Socket()
  {
    return (EAttribute)processorEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getProcessor_Cores()
  {
    return (EAttribute)processorEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGraphicsCard()
  {
    return graphicsCardEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGraphicsCard_Power()
  {
    return (EAttribute)graphicsCardEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGraphicsCard_Model()
  {
    return (EAttribute)graphicsCardEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGraphicsCard_Vram()
  {
    return (EAttribute)graphicsCardEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMemory()
  {
    return memoryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMemory_Power()
  {
    return (EAttribute)memoryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMemory_Type()
  {
    return (EAttribute)memoryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMemory_Capacity()
  {
    return (EAttribute)memoryEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStorage()
  {
    return storageEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStorage_Power()
  {
    return (EAttribute)storageEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStorage_Type()
  {
    return (EAttribute)storageEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStorage_Capacity()
  {
    return (EAttribute)storageEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDrive()
  {
    return driveEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDrive_Power()
  {
    return (EAttribute)driveEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDrive_Type()
  {
    return (EAttribute)driveEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPeripheral()
  {
    return peripheralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPeripheral_Kind()
  {
    return (EAttribute)peripheralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPeripheral_Power()
  {
    return (EAttribute)peripheralEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPeripheral_Port()
  {
    return (EAttribute)peripheralEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPowerSupply()
  {
    return powerSupplyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPowerSupply_Capacity()
  {
    return (EAttribute)powerSupplyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPowerSupply_Rating()
  {
    return (EAttribute)powerSupplyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getPeripheralKind()
  {
    return peripheralKindEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getMotherboardType()
  {
    return motherboardTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getSocket()
  {
    return socketEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getPort()
  {
    return portEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getMemoryType()
  {
    return memoryTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getStorageType()
  {
    return storageTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getDriveType()
  {
    return driveTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getRating()
  {
    return ratingEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComputerDslFactory getComputerDslFactory()
  {
    return (ComputerDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__ELEMENTS);

    abstractElementEClass = createEClass(ABSTRACT_ELEMENT);

    packageDeclarationEClass = createEClass(PACKAGE_DECLARATION);
    createEAttribute(packageDeclarationEClass, PACKAGE_DECLARATION__NAME);
    createEReference(packageDeclarationEClass, PACKAGE_DECLARATION__ELEMENTS);

    importEClass = createEClass(IMPORT);
    createEAttribute(importEClass, IMPORT__IMPORTED_NAMESPACE);

    computerEClass = createEClass(COMPUTER);
    createEAttribute(computerEClass, COMPUTER__NAME);
    createEReference(computerEClass, COMPUTER__MOTHERBOARD);
    createEReference(computerEClass, COMPUTER__PROCESSOR);
    createEReference(computerEClass, COMPUTER__GRAPHICS_CARD);
    createEReference(computerEClass, COMPUTER__MEMORY);
    createEReference(computerEClass, COMPUTER__STORAGE);
    createEReference(computerEClass, COMPUTER__DRIVE);
    createEReference(computerEClass, COMPUTER__PERIPHERALS);
    createEReference(computerEClass, COMPUTER__POWER_SUPPLY);

    partEClass = createEClass(PART);
    createEAttribute(partEClass, PART__NAME);

    motherboardEClass = createEClass(MOTHERBOARD);
    createEAttribute(motherboardEClass, MOTHERBOARD__POWER);
    createEAttribute(motherboardEClass, MOTHERBOARD__TYPE);
    createEAttribute(motherboardEClass, MOTHERBOARD__CHIPSET);
    createEAttribute(motherboardEClass, MOTHERBOARD__SOCKET);
    createEAttribute(motherboardEClass, MOTHERBOARD__PORTS);

    processorEClass = createEClass(PROCESSOR);
    createEAttribute(processorEClass, PROCESSOR__POWER);
    createEAttribute(processorEClass, PROCESSOR__MODEL);
    createEAttribute(processorEClass, PROCESSOR__SOCKET);
    createEAttribute(processorEClass, PROCESSOR__CORES);

    graphicsCardEClass = createEClass(GRAPHICS_CARD);
    createEAttribute(graphicsCardEClass, GRAPHICS_CARD__POWER);
    createEAttribute(graphicsCardEClass, GRAPHICS_CARD__MODEL);
    createEAttribute(graphicsCardEClass, GRAPHICS_CARD__VRAM);

    memoryEClass = createEClass(MEMORY);
    createEAttribute(memoryEClass, MEMORY__POWER);
    createEAttribute(memoryEClass, MEMORY__TYPE);
    createEAttribute(memoryEClass, MEMORY__CAPACITY);

    storageEClass = createEClass(STORAGE);
    createEAttribute(storageEClass, STORAGE__POWER);
    createEAttribute(storageEClass, STORAGE__TYPE);
    createEAttribute(storageEClass, STORAGE__CAPACITY);

    driveEClass = createEClass(DRIVE);
    createEAttribute(driveEClass, DRIVE__POWER);
    createEAttribute(driveEClass, DRIVE__TYPE);

    peripheralEClass = createEClass(PERIPHERAL);
    createEAttribute(peripheralEClass, PERIPHERAL__KIND);
    createEAttribute(peripheralEClass, PERIPHERAL__POWER);
    createEAttribute(peripheralEClass, PERIPHERAL__PORT);

    powerSupplyEClass = createEClass(POWER_SUPPLY);
    createEAttribute(powerSupplyEClass, POWER_SUPPLY__CAPACITY);
    createEAttribute(powerSupplyEClass, POWER_SUPPLY__RATING);

    // Create enums
    peripheralKindEEnum = createEEnum(PERIPHERAL_KIND);
    motherboardTypeEEnum = createEEnum(MOTHERBOARD_TYPE);
    socketEEnum = createEEnum(SOCKET);
    portEEnum = createEEnum(PORT);
    memoryTypeEEnum = createEEnum(MEMORY_TYPE);
    storageTypeEEnum = createEEnum(STORAGE_TYPE);
    driveTypeEEnum = createEEnum(DRIVE_TYPE);
    ratingEEnum = createEEnum(RATING);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    packageDeclarationEClass.getESuperTypes().add(this.getAbstractElement());
    importEClass.getESuperTypes().add(this.getAbstractElement());
    computerEClass.getESuperTypes().add(this.getAbstractElement());
    partEClass.getESuperTypes().add(this.getAbstractElement());
    motherboardEClass.getESuperTypes().add(this.getPart());
    processorEClass.getESuperTypes().add(this.getPart());
    graphicsCardEClass.getESuperTypes().add(this.getPart());
    memoryEClass.getESuperTypes().add(this.getPart());
    storageEClass.getESuperTypes().add(this.getPart());
    driveEClass.getESuperTypes().add(this.getPart());
    peripheralEClass.getESuperTypes().add(this.getPart());
    powerSupplyEClass.getESuperTypes().add(this.getPart());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Elements(), this.getAbstractElement(), null, "elements", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(abstractElementEClass, AbstractElement.class, "AbstractElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(packageDeclarationEClass, PackageDeclaration.class, "PackageDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPackageDeclaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, PackageDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPackageDeclaration_Elements(), this.getAbstractElement(), null, "elements", null, 0, -1, PackageDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(importEClass, Import.class, "Import", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImport_ImportedNamespace(), ecorePackage.getEString(), "importedNamespace", null, 0, 1, Import.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(computerEClass, Computer.class, "Computer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComputer_Name(), ecorePackage.getEString(), "name", null, 0, 1, Computer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComputer_Motherboard(), this.getMotherboard(), null, "motherboard", null, 0, 1, Computer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComputer_Processor(), this.getProcessor(), null, "processor", null, 0, 1, Computer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComputer_GraphicsCard(), this.getGraphicsCard(), null, "graphicsCard", null, 0, 1, Computer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComputer_Memory(), this.getMemory(), null, "memory", null, 0, -1, Computer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComputer_Storage(), this.getStorage(), null, "storage", null, 0, -1, Computer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComputer_Drive(), this.getDrive(), null, "drive", null, 0, 1, Computer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComputer_Peripherals(), this.getPeripheral(), null, "peripherals", null, 0, -1, Computer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComputer_PowerSupply(), this.getPowerSupply(), null, "powerSupply", null, 0, 1, Computer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(partEClass, Part.class, "Part", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPart_Name(), ecorePackage.getEString(), "name", null, 0, 1, Part.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(motherboardEClass, Motherboard.class, "Motherboard", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMotherboard_Power(), ecorePackage.getEInt(), "power", null, 0, 1, Motherboard.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMotherboard_Type(), this.getMotherboardType(), "type", null, 0, 1, Motherboard.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMotherboard_Chipset(), ecorePackage.getEString(), "chipset", null, 0, 1, Motherboard.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMotherboard_Socket(), this.getSocket(), "socket", null, 0, 1, Motherboard.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMotherboard_Ports(), this.getPort(), "ports", null, 0, -1, Motherboard.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(processorEClass, Processor.class, "Processor", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getProcessor_Power(), ecorePackage.getEInt(), "power", null, 0, 1, Processor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getProcessor_Model(), ecorePackage.getEString(), "model", null, 0, 1, Processor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getProcessor_Socket(), this.getSocket(), "socket", null, 0, 1, Processor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getProcessor_Cores(), ecorePackage.getEInt(), "cores", null, 0, 1, Processor.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(graphicsCardEClass, GraphicsCard.class, "GraphicsCard", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGraphicsCard_Power(), ecorePackage.getEInt(), "power", null, 0, 1, GraphicsCard.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGraphicsCard_Model(), ecorePackage.getEString(), "model", null, 0, 1, GraphicsCard.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGraphicsCard_Vram(), ecorePackage.getEInt(), "vram", null, 0, 1, GraphicsCard.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(memoryEClass, Memory.class, "Memory", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMemory_Power(), ecorePackage.getEInt(), "power", null, 0, 1, Memory.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMemory_Type(), this.getMemoryType(), "type", null, 0, 1, Memory.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMemory_Capacity(), ecorePackage.getEInt(), "capacity", null, 0, 1, Memory.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(storageEClass, Storage.class, "Storage", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStorage_Power(), ecorePackage.getEInt(), "power", null, 0, 1, Storage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStorage_Type(), this.getStorageType(), "type", null, 0, 1, Storage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStorage_Capacity(), ecorePackage.getEInt(), "capacity", null, 0, 1, Storage.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(driveEClass, Drive.class, "Drive", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDrive_Power(), ecorePackage.getEInt(), "power", null, 0, 1, Drive.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDrive_Type(), this.getDriveType(), "type", null, 0, 1, Drive.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(peripheralEClass, Peripheral.class, "Peripheral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPeripheral_Kind(), this.getPeripheralKind(), "kind", null, 0, 1, Peripheral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPeripheral_Power(), ecorePackage.getEInt(), "power", null, 0, 1, Peripheral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPeripheral_Port(), this.getPort(), "port", null, 0, 1, Peripheral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(powerSupplyEClass, PowerSupply.class, "PowerSupply", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPowerSupply_Capacity(), ecorePackage.getEInt(), "capacity", null, 0, 1, PowerSupply.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPowerSupply_Rating(), this.getRating(), "rating", null, 0, 1, PowerSupply.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(peripheralKindEEnum, PeripheralKind.class, "PeripheralKind");
    addEEnumLiteral(peripheralKindEEnum, PeripheralKind.MONITOR);
    addEEnumLiteral(peripheralKindEEnum, PeripheralKind.KEYBOARD);
    addEEnumLiteral(peripheralKindEEnum, PeripheralKind.MOUSE);
    addEEnumLiteral(peripheralKindEEnum, PeripheralKind.PRINTER);

    initEEnum(motherboardTypeEEnum, MotherboardType.class, "MotherboardType");
    addEEnumLiteral(motherboardTypeEEnum, MotherboardType.ATX);
    addEEnumLiteral(motherboardTypeEEnum, MotherboardType.MICRO_ATX);
    addEEnumLiteral(motherboardTypeEEnum, MotherboardType.MINI_ITX);

    initEEnum(socketEEnum, Socket.class, "Socket");
    addEEnumLiteral(socketEEnum, Socket.AM4);
    addEEnumLiteral(socketEEnum, Socket.AM5);
    addEEnumLiteral(socketEEnum, Socket.LGA1200);
    addEEnumLiteral(socketEEnum, Socket.LGA1700);

    initEEnum(portEEnum, Port.class, "Port");
    addEEnumLiteral(portEEnum, Port.USB);
    addEEnumLiteral(portEEnum, Port.PS2);
    addEEnumLiteral(portEEnum, Port.HDMI);
    addEEnumLiteral(portEEnum, Port.DISPLAY_PORT);
    addEEnumLiteral(portEEnum, Port.VGA);
    addEEnumLiteral(portEEnum, Port.ETHERNET);
    addEEnumLiteral(portEEnum, Port.AUDIO);

    initEEnum(memoryTypeEEnum, MemoryType.class, "MemoryType");
    addEEnumLiteral(memoryTypeEEnum, MemoryType.DDR4);
    addEEnumLiteral(memoryTypeEEnum, MemoryType.DDR5);

    initEEnum(storageTypeEEnum, StorageType.class, "StorageType");
    addEEnumLiteral(storageTypeEEnum, StorageType.HDD);
    addEEnumLiteral(storageTypeEEnum, StorageType.SSD);

    initEEnum(driveTypeEEnum, DriveType.class, "DriveType");
    addEEnumLiteral(driveTypeEEnum, DriveType.CD_ROM);
    addEEnumLiteral(driveTypeEEnum, DriveType.CD_R);
    addEEnumLiteral(driveTypeEEnum, DriveType.CD_RW);
    addEEnumLiteral(driveTypeEEnum, DriveType.DVD_ROM);
    addEEnumLiteral(driveTypeEEnum, DriveType.BLU_RAY);

    initEEnum(ratingEEnum, Rating.class, "Rating");
    addEEnumLiteral(ratingEEnum, Rating.BRONZE);
    addEEnumLiteral(ratingEEnum, Rating.SILVER);
    addEEnumLiteral(ratingEEnum, Rating.GOLD);
    addEEnumLiteral(ratingEEnum, Rating.PLATINUM);
    addEEnumLiteral(ratingEEnum, Rating.TITANIUM);

    // Create resource
    createResource(eNS_URI);
  }

} //ComputerDslPackageImpl
