/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.computer.computerDsl.ComputerDslPackage;
import org.xtext.example.computer.computerDsl.Peripheral;
import org.xtext.example.computer.computerDsl.PeripheralKind;
import org.xtext.example.computer.computerDsl.Port;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Peripheral</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.PeripheralImpl#getKind <em>Kind</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.PeripheralImpl#getPower <em>Power</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.PeripheralImpl#getPort <em>Port</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PeripheralImpl extends PartImpl implements Peripheral
{
  /**
   * The default value of the '{@link #getKind() <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKind()
   * @generated
   * @ordered
   */
  protected static final PeripheralKind KIND_EDEFAULT = PeripheralKind.MONITOR;

  /**
   * The cached value of the '{@link #getKind() <em>Kind</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKind()
   * @generated
   * @ordered
   */
  protected PeripheralKind kind = KIND_EDEFAULT;

  /**
   * The default value of the '{@link #getPower() <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPower()
   * @generated
   * @ordered
   */
  protected static final int POWER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPower() <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPower()
   * @generated
   * @ordered
   */
  protected int power = POWER_EDEFAULT;

  /**
   * The default value of the '{@link #getPort() <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPort()
   * @generated
   * @ordered
   */
  protected static final Port PORT_EDEFAULT = Port.USB;

  /**
   * The cached value of the '{@link #getPort() <em>Port</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPort()
   * @generated
   * @ordered
   */
  protected Port port = PORT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PeripheralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComputerDslPackage.Literals.PERIPHERAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PeripheralKind getKind()
  {
    return kind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKind(PeripheralKind newKind)
  {
    PeripheralKind oldKind = kind;
    kind = newKind == null ? KIND_EDEFAULT : newKind;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.PERIPHERAL__KIND, oldKind, kind));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPower()
  {
    return power;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPower(int newPower)
  {
    int oldPower = power;
    power = newPower;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.PERIPHERAL__POWER, oldPower, power));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Port getPort()
  {
    return port;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPort(Port newPort)
  {
    Port oldPort = port;
    port = newPort == null ? PORT_EDEFAULT : newPort;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.PERIPHERAL__PORT, oldPort, port));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComputerDslPackage.PERIPHERAL__KIND:
        return getKind();
      case ComputerDslPackage.PERIPHERAL__POWER:
        return getPower();
      case ComputerDslPackage.PERIPHERAL__PORT:
        return getPort();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComputerDslPackage.PERIPHERAL__KIND:
        setKind((PeripheralKind)newValue);
        return;
      case ComputerDslPackage.PERIPHERAL__POWER:
        setPower((Integer)newValue);
        return;
      case ComputerDslPackage.PERIPHERAL__PORT:
        setPort((Port)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComputerDslPackage.PERIPHERAL__KIND:
        setKind(KIND_EDEFAULT);
        return;
      case ComputerDslPackage.PERIPHERAL__POWER:
        setPower(POWER_EDEFAULT);
        return;
      case ComputerDslPackage.PERIPHERAL__PORT:
        setPort(PORT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComputerDslPackage.PERIPHERAL__KIND:
        return kind != KIND_EDEFAULT;
      case ComputerDslPackage.PERIPHERAL__POWER:
        return power != POWER_EDEFAULT;
      case ComputerDslPackage.PERIPHERAL__PORT:
        return port != PORT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (kind: ");
    result.append(kind);
    result.append(", power: ");
    result.append(power);
    result.append(", port: ");
    result.append(port);
    result.append(')');
    return result.toString();
  }

} //PeripheralImpl
