/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.computer.computerDsl.ComputerDslPackage;
import org.xtext.example.computer.computerDsl.PowerSupply;
import org.xtext.example.computer.computerDsl.Rating;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Power Supply</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.PowerSupplyImpl#getCapacity <em>Capacity</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.PowerSupplyImpl#getRating <em>Rating</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PowerSupplyImpl extends PartImpl implements PowerSupply
{
  /**
   * The default value of the '{@link #getCapacity() <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacity()
   * @generated
   * @ordered
   */
  protected static final int CAPACITY_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCapacity() <em>Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCapacity()
   * @generated
   * @ordered
   */
  protected int capacity = CAPACITY_EDEFAULT;

  /**
   * The default value of the '{@link #getRating() <em>Rating</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRating()
   * @generated
   * @ordered
   */
  protected static final Rating RATING_EDEFAULT = Rating.BRONZE;

  /**
   * The cached value of the '{@link #getRating() <em>Rating</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRating()
   * @generated
   * @ordered
   */
  protected Rating rating = RATING_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PowerSupplyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComputerDslPackage.Literals.POWER_SUPPLY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCapacity()
  {
    return capacity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCapacity(int newCapacity)
  {
    int oldCapacity = capacity;
    capacity = newCapacity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.POWER_SUPPLY__CAPACITY, oldCapacity, capacity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rating getRating()
  {
    return rating;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRating(Rating newRating)
  {
    Rating oldRating = rating;
    rating = newRating == null ? RATING_EDEFAULT : newRating;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.POWER_SUPPLY__RATING, oldRating, rating));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComputerDslPackage.POWER_SUPPLY__CAPACITY:
        return getCapacity();
      case ComputerDslPackage.POWER_SUPPLY__RATING:
        return getRating();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComputerDslPackage.POWER_SUPPLY__CAPACITY:
        setCapacity((Integer)newValue);
        return;
      case ComputerDslPackage.POWER_SUPPLY__RATING:
        setRating((Rating)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComputerDslPackage.POWER_SUPPLY__CAPACITY:
        setCapacity(CAPACITY_EDEFAULT);
        return;
      case ComputerDslPackage.POWER_SUPPLY__RATING:
        setRating(RATING_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComputerDslPackage.POWER_SUPPLY__CAPACITY:
        return capacity != CAPACITY_EDEFAULT;
      case ComputerDslPackage.POWER_SUPPLY__RATING:
        return rating != RATING_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (capacity: ");
    result.append(capacity);
    result.append(", rating: ");
    result.append(rating);
    result.append(')');
    return result.toString();
  }

} //PowerSupplyImpl
