/**
 * generated by Xtext 2.44.0
 */
package org.xtext.example.computer.computerDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.computer.computerDsl.ComputerDslPackage;
import org.xtext.example.computer.computerDsl.Processor;
import org.xtext.example.computer.computerDsl.Socket;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Processor</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ProcessorImpl#getPower <em>Power</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ProcessorImpl#getModel <em>Model</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ProcessorImpl#getSocket <em>Socket</em>}</li>
 *   <li>{@link org.xtext.example.computer.computerDsl.impl.ProcessorImpl#getCores <em>Cores</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProcessorImpl extends PartImpl implements Processor
{
  /**
   * The default value of the '{@link #getPower() <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPower()
   * @generated
   * @ordered
   */
  protected static final int POWER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPower() <em>Power</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPower()
   * @generated
   * @ordered
   */
  protected int power = POWER_EDEFAULT;

  /**
   * The default value of the '{@link #getModel() <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModel()
   * @generated
   * @ordered
   */
  protected static final String MODEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getModel() <em>Model</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModel()
   * @generated
   * @ordered
   */
  protected String model = MODEL_EDEFAULT;

  /**
   * The default value of the '{@link #getSocket() <em>Socket</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSocket()
   * @generated
   * @ordered
   */
  protected static final Socket SOCKET_EDEFAULT = Socket.AM4;

  /**
   * The cached value of the '{@link #getSocket() <em>Socket</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSocket()
   * @generated
   * @ordered
   */
  protected Socket socket = SOCKET_EDEFAULT;

  /**
   * The default value of the '{@link #getCores() <em>Cores</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCores()
   * @generated
   * @ordered
   */
  protected static final int CORES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getCores() <em>Cores</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCores()
   * @generated
   * @ordered
   */
  protected int cores = CORES_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ComputerDslPackage.Literals.PROCESSOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPower()
  {
    return power;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPower(int newPower)
  {
    int oldPower = power;
    power = newPower;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.PROCESSOR__POWER, oldPower, power));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getModel()
  {
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setModel(String newModel)
  {
    String oldModel = model;
    model = newModel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.PROCESSOR__MODEL, oldModel, model));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Socket getSocket()
  {
    return socket;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSocket(Socket newSocket)
  {
    Socket oldSocket = socket;
    socket = newSocket == null ? SOCKET_EDEFAULT : newSocket;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.PROCESSOR__SOCKET, oldSocket, socket));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getCores()
  {
    return cores;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCores(int newCores)
  {
    int oldCores = cores;
    cores = newCores;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ComputerDslPackage.PROCESSOR__CORES, oldCores, cores));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ComputerDslPackage.PROCESSOR__POWER:
        return getPower();
      case ComputerDslPackage.PROCESSOR__MODEL:
        return getModel();
      case ComputerDslPackage.PROCESSOR__SOCKET:
        return getSocket();
      case ComputerDslPackage.PROCESSOR__CORES:
        return getCores();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ComputerDslPackage.PROCESSOR__POWER:
        setPower((Integer)newValue);
        return;
      case ComputerDslPackage.PROCESSOR__MODEL:
        setModel((String)newValue);
        return;
      case ComputerDslPackage.PROCESSOR__SOCKET:
        setSocket((Socket)newValue);
        return;
      case ComputerDslPackage.PROCESSOR__CORES:
        setCores((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ComputerDslPackage.PROCESSOR__POWER:
        setPower(POWER_EDEFAULT);
        return;
      case ComputerDslPackage.PROCESSOR__MODEL:
        setModel(MODEL_EDEFAULT);
        return;
      case ComputerDslPackage.PROCESSOR__SOCKET:
        setSocket(SOCKET_EDEFAULT);
        return;
      case ComputerDslPackage.PROCESSOR__CORES:
        setCores(CORES_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ComputerDslPackage.PROCESSOR__POWER:
        return power != POWER_EDEFAULT;
      case ComputerDslPackage.PROCESSOR__MODEL:
        return MODEL_EDEFAULT == null ? model != null : !MODEL_EDEFAULT.equals(model);
      case ComputerDslPackage.PROCESSOR__SOCKET:
        return socket != SOCKET_EDEFAULT;
      case ComputerDslPackage.PROCESSOR__CORES:
        return cores != CORES_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (power: ");
    result.append(power);
    result.append(", model: ");
    result.append(model);
    result.append(", socket: ");
    result.append(socket);
    result.append(", cores: ");
    result.append(cores);
    result.append(')');
    return result.toString();
  }

} //ProcessorImpl
